[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/"
  to = "/ru/"
  status = 302
  force = true
  conditions = {Language = ["ru"]}

[[redirects]]
  from = "/"
  to = "/es/"
  status = 302
  force = true
  conditions = {Language = ["es"]}

[[redirects]]
  from = "/"
  to = "/en/"
  status = 302
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
    Permissions-Policy = "geolocation=(), camera=(), microphone=()"
    Content-Security-Policy = "default-src 'self'; font-src 'self' fonts.gstatic.com; style-src 'self' 'unsafe-inline' fonts.googleapis.com; img-src 'self' data:"
