import type { UIStrings } from '@/lib/types'

const ui: UIStrings = {
  back: '← Atrás',
  listen: 'Escuchar esta página',
  stop: 'Detener',
  noSpeech: 'Este navegador no puede leer en voz alta',
  allPages: 'Todas las páginas',
  disclaimer:
    'No somos abogados y no damos asesoría legal. Aquí solo hay hechos y enlaces a fuentes oficiales.',
  updated: 'Información actualizada el 28 de julio de 2026. Las reglas cambian — mire la fecha.',
  nav: {
    where: 'Cómo encontrarlo',
    anum: 'Dónde está el número A',
    documents: 'Qué significan estos papeles',
    firstcall: 'La primera llamada',
    verify: 'Verificar al abogado',
    connect: 'Llamadas, dinero, cartas',
    visit: 'La visita',
    journey: 'El camino',
    attorney: 'Abogado',
    habeas: 'Habeas corpus',
    docpack: 'Paquete para el abogado',
    deadlines: 'No faltar a la audiencia',
    intake: 'Su lista de tareas',
    'facility-adelanto': 'Adelanto',
    complaints: 'Si algo anda mal',
    forms: 'Diccionario de formularios',
    prepare: 'Un plan por si hay una detención',
    'state-ca': 'California',
    'state-tx': 'Texas',
    'state-la': 'Luisiana',
    orgs: 'Para organizaciones',
    about: 'Acerca de',
    data: 'Sus datos',
    disclaimer: 'No somos abogados',
  },
  navGroups: [
    { label: 'La primera noche', keys: ['intake', 'where', 'anum', 'documents', 'firstcall', 'verify'] },
    { label: 'El camino', keys: ['journey', 'connect', 'visit', 'attorney', 'habeas', 'docpack', 'deadlines'] },
    { label: 'Directorio', keys: ['state-ca', 'state-tx', 'state-la', 'facility-adelanto', 'complaints', 'forms', 'prepare'] },
    { label: 'Acerca de', keys: ['orgs', 'about', 'data', 'disclaimer'] },
  ],
  iceGate: {
    title: 'Va a abrir el sitio de ICE',
    body: [
      'Según su propio aviso de privacidad, registra la dirección IP y el dominio de cada visitante.',
      'Nosotros no le enviamos ningún dato sobre usted.',
    ],
    open: 'Abrir',
    ask: 'Pedir a otra persona que lo haga',
    askHint: 'Comparta esta dirección con alguien que pueda hacer la búsqueda:',
  },
  nameVariants: {
    label: 'Variantes de escritura del nombre — todo queda en este navegador',
    placeholder: 'Nombre y apellido tal como los conoce',
    hint: 'El nombre debe coincidir letra por letra. Marque con las casillas las variantes ya probadas.',
    // min-ok: подпись инструмента, данные не покидают браузер
  },
  aNumber: {
    label: 'Verificar el formato del número A',
    placeholder: 'Solo dígitos, 8 o 9',
    copy: 'Copiar',
    copied: 'Copiado',
    hint: 'Ocho dígitos también está bien: se agrega un cero al inicio. El número está en la pulsera — se puede pedir que lo lean en voz alta.',
  },
  printPage: 'Imprimir esta página',
  browserOnly: 'Su respuesta se queda solo en este navegador',
  national: {
    title: 'Lo que muestran los datos del país',
    median: 'La mediana de duración de una detención es de {days} días (casos concluidos, 2024–2026).',
    removal: 'Alrededor del {pct}% de estas detenciones terminaron en expulsión. Al resto lo liberaron de distintas formas o lo trasladaron a otro centro.',
    note: 'Es un agregado de datos pasados (Deportation Data Project), no un pronóstico para una persona concreta.',
  },
  officeFinder: {
    label: 'Oficina de ICE — a dónde acudir y dónde reportarse',
    placeholder: 'Ciudad o estado',
    hint: 'Escriba una ciudad o estado, en inglés. La base tiene 270 oficinas de ICE (Deportation Data Project).',
    typeField: 'Oficina de campo',
    typeSub: 'Suboficina',
    aorLabel: 'Pertenece a',
    empty: 'No se encontró una oficina para esa búsqueda. Pruebe el nombre del estado o la ciudad grande más cercana.',
    note: 'Aquí no se publican horarios ni teléfonos — confírmelos en la página oficial de ICE o llamando a la oficina.',
  },
  tabs: { home: 'Inicio', tasks: 'Tareas', docs: 'Documentos', find: 'Buscar' },
  dirEmpty: 'Aún no hay datos. No publicamos teléfonos ni direcciones sin verificar.',
  docMap: {
    title: 'Cómo se ve un aviso (un mapa)',
    formLabel: 'Notice to Appear · I-862',
    anum: 'Número A: la letra A y 9 dígitos',
    hearing: 'Fecha y hora de la audiencia (puede faltar)',
    court: 'Nombre y dirección de la corte',
    charges: 'Alegaciones y cargos',
    signature: 'Firmado por un oficial de ICE — no un juez',
    note: 'Esto es un mapa, no su documento. Las secciones y los números cambian para cada persona — compárelo con su propio papel.',
  },
  onward: {
    next: 'Siguiente paso',
    related: 'Páginas relacionadas',
    sources: 'Fuentes externas',
  },
  visitFinder: {
    label: 'El centro donde tienen a la persona',
    placeholder: 'Ciudad, nombre o estado',
    inBase: 'Escriba una ciudad, el nombre del centro o el estado — en inglés o como aparece en los documentos. La base tiene 196 centros.',
    facilityPage: 'Página del centro: correo, cartas, estado',
    notFoundTitle: 'Este centro todavía no está en nuestra base',
    notFoundBody: 'Puede ser un punto de detención temporal o un centro nuevo. El camino confiable es una llamada a donde tienen a la persona. El teléfono está en la página oficial de ICE abajo.',
    askTitle: 'Una llamada — toda la respuesta. Pregunte:',
    ask: [
      'En qué unidad de vivienda está la persona y qué horario de visitas tiene esa unidad',
      'Si hay que apuntarse antes, y cómo',
      'Qué documentos necesitan los visitantes',
      'Si pueden venir niños, y cuál es el código de vestimenta',
      'Cuántas personas pueden venir por visita',
      'Si las visitas están canceladas esta semana',
    ],
    iceLabel: 'La lista de centros de ICE con horarios de visita',
    drilNote: 'Si no logra comunicarse con el centro: 1-888-351-4024 — la línea oficial de ICE (DRIL), lun–vie 8 a.m.–8 p.m. hora del Este, hay español.',
    fieldOfficeLabel: 'Lo maneja la oficina de ICE',
    circuitLabel: 'Circuito federal',
    circuits: {
      '1': 'Primero', '2': 'Segundo', '3': 'Tercero', '4': 'Cuarto',
      '5': 'Quinto', '6': 'Sexto', '7': 'Séptimo', '8': 'Octavo',
      '9': 'Noveno', '10': 'Décimo', '11': 'Undécimo', DC: 'D.C.',
    },
    mandatoryWarn: 'En este circuito federal el gobierno insiste en la detención obligatoria — aquí es más difícil lograr la salida. Qué caminos son reales lo determina un abogado (vea «Los caminos de salida»). Estado a julio de 2026.',
    iceHours: 'El horario de visitas cambia por unidad de vivienda y sin aviso. Para el actual: abra la página de este centro en ICE o llame y pregunte en qué unidad está la persona y las horas de esa unidad.',
    scheduleLink: 'Buscar el horario de este centro',
    provenance: 'Direcciones y circuitos: datos de ICE recopilados por el Deportation Data Project (junio de 2026). Los horarios y teléfonos no se publican ahí — confirme en la página de ICE o por teléfono.',
    moreResults: 'Se muestran los primeros 12 — precise la búsqueda: ciudad o nombre exacto.',
    stayTitle: 'Cuánto suelen estar detenidas las personas en este centro',
    stayLine: 'Mediana {med} días; para la mitad de las personas, de {p25} a {p75}. Según {n} casos concluidos en 2024–2026.',
    stayNote: 'Es un dato de datos pasados, no un pronóstico para una persona concreta. Fuente: Deportation Data Project.',
  },
  docPack: {
    // min-ok: подписи разделов инструмента, файлы не покидают браузер
    sections: {
      home: 'Dirección y vivienda',
      years: 'Años de residencia',
      family: 'Familia',
      work: 'Trabajo',
      courts: 'Asistencia a la corte',
      court: 'Papeles de la corte y de la agencia',
      med: 'Médico',
      other: 'Otros',
    },
    addPhoto: '+ Foto',
    processing: 'Procesando…',
    labelPlaceholder: 'Qué es y de qué año',
    remove: 'Quitar',
    pages: ['página', 'páginas', 'páginas'],
    anumLabel: 'Número A, si lo sabe — para el nombre del archivo, sin el nombre de la persona',
    anumHint: 'Solo dígitos, se puede dejar vacío',
    makePdf: 'Armar el paquete PDF',
    making: 'Armando…',
    empty: 'vacío por ahora',
    share: 'Compartir',
    download: 'Descargar',
    print: 'Abrir para imprimir',
    shareUnavailable: 'Este dispositivo no tiene «Compartir» del sistema — descargue el archivo y adjúntelo usted mismo.',
    deleteAll: 'Borrar todas las fotos del navegador',
    deleteAllConfirm: '¿Borrar de verdad? Toque otra vez',
    storageNote: 'Las fotos se guardan solo en este navegador. No las vemos ni las recibimos. Después de enviar el paquete se pueden borrar con un botón.',
    readyTitle: 'El paquete está listo',
    readyHint: '«Compartir» abre el menú de su propio teléfono: correo, WhatsApp — lo que usted usa. Nuestro servidor no participa.',
    partLabel: 'Parte',
    cover: {
      title: 'Paquete de documentos para el abogado',
      date: 'Fecha',
      packet: 'Paquete n.º',
      supplements: 'Complementa el paquete n.º {n} del {date}',
      noAnum: 'Número A no indicado',
      toc: 'Qué hay dentro',
      missing: 'Qué falta todavía',
      missingNote: 'La lista de lo que falta es más honesta que la de logros: le ahorra al abogado la primera conversación.',
      pagesWord: 'pág.',
      part: 'Parte {i} de {n}',
      footer: 'Armado por la familia en el navegador vía detnav.com. Los archivos no pasaron por ningún servidor. No somos abogados; qué debe llevar el paquete lo determina el abogado.',
    },
  },
}

export default ui
