import type { UIStrings } from '@/lib/types'

const ui: UIStrings = {
  back: '← Atrás',
  listen: 'Escuchar esta página',
  stop: 'Detener',
  noSpeech: 'Este navegador no puede leer en voz alta',
  allPages: 'Todas las páginas',
  disclaimer:
    'No somos abogados y no damos asesoría legal. Aquí solo hay hechos y enlaces a fuentes oficiales.',
  updated: 'Información actualizada el 28 de julio de 2026. Las reglas cambian — mire la fecha.',
  nav: {
    where: 'Cómo encontrarlo',
    anum: 'Dónde está el número A',
    documents: 'Qué significan estos papeles',
    firstcall: 'La primera llamada',
    verify: 'Verificar al abogado',
    connect: 'Llamadas, dinero, cartas',
    journey: 'El camino',
    attorney: 'Abogado',
    habeas: 'Habeas corpus',
    docpack: 'Paquete para el abogado',
    deadlines: 'No faltar a la audiencia',
    intake: 'Su lista de tareas',
    'facility-adelanto': 'Adelanto',
    'state-ca': 'California',
    'state-tx': 'Texas',
    'state-la': 'Luisiana',
    orgs: 'Para organizaciones',
    about: 'Acerca de',
    data: 'Sus datos',
    disclaimer: 'No somos abogados',
  },
  navGroups: [
    { label: 'La primera noche', keys: ['intake', 'where', 'anum', 'documents', 'firstcall', 'verify'] },
    { label: 'El camino', keys: ['journey', 'connect', 'attorney', 'habeas', 'docpack', 'deadlines'] },
    { label: 'Directorio', keys: ['state-ca', 'state-tx', 'state-la', 'facility-adelanto'] },
    { label: 'Acerca de', keys: ['orgs', 'about', 'data', 'disclaimer'] },
  ],
  iceGate: {
    title: 'Va a abrir el sitio de ICE',
    body: [
      'Según su propio aviso de privacidad, registra la dirección IP y el dominio de cada visitante.',
      'Nosotros no le enviamos ningún dato sobre usted.',
    ],
    open: 'Abrir',
    ask: 'Pedir a otra persona que lo haga',
    askHint: 'Comparta esta dirección con alguien que pueda hacer la búsqueda:',
  },
  nameVariants: {
    label: 'Variantes de escritura del nombre — todo queda en este navegador',
    placeholder: 'Nombre y apellido tal como los conoce',
    hint: 'El nombre debe coincidir letra por letra. Marque con las casillas las variantes ya probadas.',
    // min-ok: подпись инструмента, данные не покидают браузер
  },
  aNumber: {
    label: 'Verificar el formato del número A',
    placeholder: 'Solo dígitos, 8 o 9',
    copy: 'Copiar',
    copied: 'Copiado',
    hint: 'Ocho dígitos también está bien: se agrega un cero al inicio. El número está en la pulsera — se puede pedir que lo lean en voz alta.',
  },
  printPage: 'Imprimir esta página',
  dirEmpty: 'Aún no hay datos. No publicamos teléfonos ni direcciones sin verificar.',
  docPack: {
    // min-ok: подписи разделов инструмента, файлы не покидают браузер
    sections: {
      home: 'Dirección y vivienda',
      years: 'Años de residencia',
      family: 'Familia',
      work: 'Trabajo',
      courts: 'Asistencia a la corte',
      court: 'Papeles de la corte y de la agencia',
      med: 'Médico',
      other: 'Otros',
    },
    addPhoto: '+ Foto',
    processing: 'Procesando…',
    labelPlaceholder: 'Qué es y de qué año',
    remove: 'Quitar',
    pages: ['página', 'páginas', 'páginas'],
    anumLabel: 'Número A, si lo sabe — para el nombre del archivo, sin el nombre de la persona',
    anumHint: 'Solo dígitos, se puede dejar vacío',
    makePdf: 'Armar el paquete PDF',
    making: 'Armando…',
    empty: 'vacío por ahora',
    share: 'Compartir',
    download: 'Descargar',
    print: 'Abrir para imprimir',
    shareUnavailable: 'Este dispositivo no tiene «Compartir» del sistema — descargue el archivo y adjúntelo usted mismo.',
    deleteAll: 'Borrar todas las fotos del navegador',
    deleteAllConfirm: '¿Borrar de verdad? Toque otra vez',
    storageNote: 'Las fotos se guardan solo en este navegador. No las vemos ni las recibimos. Después de enviar el paquete se pueden borrar con un botón.',
    readyTitle: 'El paquete está listo',
    readyHint: '«Compartir» abre el menú de su propio teléfono: correo, WhatsApp — lo que usted usa. Nuestro servidor no participa.',
    partLabel: 'Parte',
    cover: {
      title: 'Paquete de documentos para el abogado',
      date: 'Fecha',
      packet: 'Paquete n.º',
      supplements: 'Complementa el paquete n.º {n} del {date}',
      noAnum: 'Número A no indicado',
      toc: 'Qué hay dentro',
      missing: 'Qué falta todavía',
      missingNote: 'La lista de lo que falta es más honesta que la de logros: le ahorra al abogado la primera conversación.',
      pagesWord: 'pág.',
      part: 'Parte {i} de {n}',
      footer: 'Armado por la familia en el navegador vía detnav.com. Los archivos no pasaron por ningún servidor. No somos abogados; qué debe llevar el paquete lo determina el abogado.',
    },
  },
}

export default ui
