// G-CHECKER-PALETTE: free accessible colour-palette generator magnet page under
// /checkers/color-palette-generator/, sixth tool in the /checkers/ family. Same
// template as the other checkers: chisto client-side (hue rotation math from
// src/lib/palette.ts, contrast math reused from src/lib/contrast.ts, zero
// server cost) but prerendered, so it lives in both hardcoded lists
// (page-lists.test.mjs). Interactivity + hydration discipline is in
// src/components/ColorPaletteGenerator.tsx.
//
// THE ANGLE: unlike a generic palette tool, every generated colour shows its
// WCAG contrast — this is a checker that happens to generate palettes, not a
// palette tool with contrast bolted on. Stated on the page itself, not just in
// code comments (same honesty discipline as the other checkers).

import { Link } from 'react-router-dom'
import { Layout } from '@/components/Layout'
import { ColorPaletteGenerator } from '@/components/ColorPaletteGenerator'
import { JsonLd, ORIGIN, SITE_NAME } from '@/lib/seo'
import { paths } from '@/lib/data'

const WCAG_143 = 'https://www.w3.org/WAI/WCAG22/Understanding/contrast-minimum.html'

export default function ColorPaletteGeneratorPage() {
  const title = 'Accessible colour palette generator — with WCAG contrast'
  const description =
    'Free colour palette generator that shows the WCAG contrast of every colour it creates. Pick a base colour and a scheme — complementary, analogous, triadic, tetradic, split-complementary or monochromatic — and see each swatch’s readable text colour, contrast ratio and AA pass/fail. No sign-up.'

  return (
    <Layout title={title} description={description} path={paths.colorPaletteGenerator()}>
      <JsonLd
        data={{
          '@context': 'https://schema.org',
          '@type': 'WebApplication',
          name: 'Verscala colour palette generator',
          description,
          url: `${ORIGIN}${paths.colorPaletteGenerator()}`,
          applicationCategory: 'DeveloperApplication',
          operatingSystem: 'Any',
          browserRequirements: 'Requires JavaScript',
          isAccessibleForFree: true,
          offers: { '@type': 'Offer', price: '0', priceCurrency: 'EUR' },
          publisher: { '@type': 'Organization', name: SITE_NAME },
        }}
      />

      <h1 className="h1 max-w-3xl">Accessible colour palette generator</h1>
      <p className="lede max-w-3xl">
        Pick a base colour and a scheme, and get a harmonious palette — but unlike a typical palette
        tool, every swatch here also shows its real WCAG contrast: the more readable of black or
        white text, the exact ratio, and a Level AA pass or fail. An accessible palette, not just a
        pretty one. Free, instant, no sign-up.
      </p>

      <ColorPaletteGenerator />

      <section className="mt-14 max-w-3xl">
        <h2 className="h2">Why accessible palettes matter</h2>
        <p className="mt-2 text-on-surface-variant">
          A palette that looks good in a mood board can still fail real readers. If the text colour
          you plan to put on a swatch does not have enough contrast against it, people with low
          vision, many older users, and anyone in bright sunlight or on a low-quality screen will
          struggle to read it — regardless of how well the hues go together. Contrast is not a matter
          of taste; it is a measurable, testable property of two colours.
        </p>
        <h3 className="mt-6 text-lg font-semibold text-on-surface">How the contrast is computed</h3>
        <p className="mt-2 text-on-surface-variant">
          For each swatch, we compute the WCAG contrast ratio against both pure black and pure white
          and keep whichever is higher — the same relative-luminance formula defined by{' '}
          <a className="underline underline-offset-2" href={WCAG_143} rel="noopener noreferrer">
            WCAG 2.2 Understanding 1.4.3
          </a>{' '}
          and used by our own scanner. The badge reads &ldquo;Pass&rdquo; when that ratio reaches{' '}
          <span className="num">4.5:1</span>, the Level AA threshold for normal text. Want to check
          contrast between two colours of your own choosing — say, a swatch as a background behind a
          specific text colour? Use the{' '}
          <Link className="underline underline-offset-2" to={paths.contrastChecker()}>
            full contrast checker
          </Link>
          .
        </p>
      </section>

      <section className="mt-14 max-w-3xl">
        <div className="rounded-xl border border-outline-variant bg-surface-container-low p-4 text-sm text-on-surface-variant">
          <p>
            <strong className="text-on-surface">What this does — and doesn&rsquo;t.</strong> The
            colour scheme (complementary, triadic, and so on) is generated by rotating hue on a
            standard colour wheel — that part is aesthetic guidance, and reasonable people can
            disagree on which scheme looks best for a given project. The contrast ratio and AA
            pass/fail next to each swatch are not guidance — they are exact arithmetic against the
            published WCAG formula. Trust the numbers for accessibility decisions; treat the harmony
            as a starting point for your own eye.
          </p>
        </div>
      </section>

      {/* МОСТ В ПРОДУКТ: сгенерировал палитру → а весь сайт? */}
      <section className="mt-14 max-w-3xl">
        <h2 className="h2">A palette is a start. Your whole site is more.</h2>
        <p className="mt-2 text-on-surface-variant">
          Getting your colours right is one important step. Point our free scanner at a real URL and
          it checks the whole page against WCAG 2.2 — contrast included — and tells you what to fix
          first, with the legal context for the site&rsquo;s jurisdiction.
        </p>
        <div className="mt-5 flex flex-wrap items-center gap-3">
          <Link className="btn" to={paths.scan()}>
            Scan a full page — free
          </Link>
          <Link className="underline underline-offset-2 text-sm" to={paths.agencies()}>
            Or find a specialist to fix it →
          </Link>
        </div>
        <p className="mt-4 text-sm text-on-surface-variant">
          Want the full pass/fail matrix for one colour pair?{' '}
          <Link className="underline underline-offset-2" to={paths.contrastChecker()}>
            Try the contrast checker
          </Link>
          , or see{' '}
          <Link className="underline underline-offset-2" to={paths.methodology()}>
            what our scanner covers
          </Link>
          , criterion by criterion.
        </p>
      </section>
    </Layout>
  )
}
