import type { IntakeContent } from '@/lib/types'

// Translated from the Russian master (content/intake/ru.ts). The wording is
// calibrated for the ban on unlicensed practice of law — do not rewrite.

const c: IntakeContent = {
  ui: {
    done: 'done',
    reassure: 'If you do not know — say so. That is a normal answer, and it also turns into a task.',
    backBtn: 'Back',
    nextBtn: 'Next',
    resultEyebrow: 'Your list',
    resultTitle: 'tasks',
    resultHint:
      'Built from your answers. Nothing went to our server — the list lives only in this browser. Tap a task to expand it.',
    resultIntro:
      'Do not worry: all of this can be handled, and not in one day. Go step by step from the top — inside each task it says why it matters, how to do it, and where exactly to get things. Many tasks link to a detailed instruction page. Save or print the list so it does not get lost.',
    moreLabel: 'Detailed instructions',
    groups: { now: 'Now', soon: 'This week', later: 'When there is time' },
    whyPrefix: 'why it is on the list',
    sections: {
      why: 'Why',
      how: 'How',
      src: 'Where exactly to get it',
      info: 'Reference',
      say: 'What to say',
      sayTag: 'SAMPLE · ADJUST TO YOUR OWN WORDS',
      form: 'Form',
      warn: 'Caution',
    },
    evBadge: 'EVIDENCE',
    evNote: {
      h: 'About the "evidence" tag',
      p: 'It marks tasks from the list of factors considered in bond decisions: address, length of residence, family ties, work, court appearances, criminal history. The list comes from a published decision of the BIA — the top immigration appeals court, whose decisions all immigration judges follow. We do not assess your situation and do not predict the outcome — we only list what is usually supported with documents.',
    },
    zoneBNote: {
      h: 'What to do with this list next',
      p: 'Download or print it — this is the draft of the package for the attorney. Attorneys bill by the minute: a family that arrives with an ordered list and documents pays for work on the case, not for sorting papers. Also prepare answers to the questions the attorney will ask first: year and manner of entry, past cases and orders, past detentions. They are not asked here and are not shown on screen — that conversation is for the attorney only.',
    },
    printBtn: 'Save or print',
    againBtn: 'Start over',
    foot: 'We are not attorneys and we do not give legal advice. This is a task list, not a legal position. The samples are everyday correspondence; we do not draft legal documents.',
  },

  questions: {
    role: {
      bn: 'Framing',
      q: 'Are you filling this out for yourself or for another person?',
      hint: 'The task lists come out different. For yourself — preparing for the future; for another — what to do right now.',
      o: {
        self: { t: 'For myself', s: 'I want to prepare in advance' },
        other: { t: 'For another person', s: 'He was detained, or it is possible' },
      },
    },
    state: {
      bn: 'Framing',
      q: { self: 'Where do things stand for you?', other: 'What happened?' },
      hint: 'This decides what comes first on the list: urgent steps or calm preparation.',
      o: {
        nothing: { t: { self: 'Nothing so far', other: 'Nothing has happened yet' } },
        case: { t: 'There is an open case in court' },
        before: { t: 'Detained before, free now' },
        just: { t: 'Detained today or yesterday' },
        found: { t: 'Already found in the system' },
        court: { t: 'There has already been a hearing' },
      },
    },
    anum: {
      bn: 'Identification',
      q: { self: 'Do you know your A-Number?', other: 'Is his A-Number known?' },
      hint: 'The letter A and nine digits. It is on the work permit, the green card, letters from the court and from USCIS — the agency that issues work permits and green cards.',
      o: {
        yes: { t: 'Yes, I know it' },
        find: { t: 'No, but there are documents at home' },
        no: { t: 'No, and there are no documents' },
        what: { t: 'I do not know what that is', d: true },
      },
    },
    idb: {
      bn: 'Identification',
      q: 'Do you know his full name, date of birth and country of birth?',
      hint: 'If the A-Number is unknown, the search uses these three fields. The spelling of the name must match the document.',
      o: {
        all: { t: 'I know everything' },
        part: { t: 'I know some of it' },
        no: { t: 'Almost nothing', d: true },
      },
    },
    years: {
      bn: 'Ties',
      q: { self: 'How many years have you been in the US?', other: 'How many years has he been in the US?' },
      hint: 'Length of residence is one of the factors a judge considers in a bond decision.',
      o: {
        lt1: { t: 'Less than a year' },
        '1_5': { t: 'One to five' },
        '5_10': { t: 'Five to ten' },
        gt10: { t: 'More than ten' },
        dunno: { t: 'I do not know', d: true },
      },
    },
    home: {
      bn: 'Ties',
      q: {
        self: 'Is the lease or the property in your name?',
        other: 'Whose name is the housing in?',
      },
      hint: 'A lease and bills show the person has a permanent home. It is one of the things a judge looks at in a bond decision.',
      o: {
        me: { t: { self: 'Yes, mine', other: 'Mine' } },
        him: { t: 'His' },
        both: { t: 'Both of ours' },
        other: { t: 'No, another person’s' },
        none: { t: 'There is no lease' },
        dunno: { t: 'I do not know', d: true },
      },
    },
    usfam: {
      bn: 'Ties',
      q: {
        self: 'Do you have close family in the US with citizenship or a green card?',
        other: 'Does he have close family in the US with citizenship or a green card?',
      },
      hint: 'Judges give particular weight to spouses and children who are citizens or green card holders.',
      o: {
        close: { t: 'Yes, a spouse or children' },
        other: { t: 'Yes, other relatives' },
        no: { t: 'No' },
        dunno: { t: 'I do not know', d: true },
      },
    },
    work: {
      bn: 'Ties',
      q: { self: 'How do things stand with work for you?', other: 'How do things stand with work for him?' },
      hint: 'Work is also proof of ties. We will point out exactly how to document it.',
      o: {
        official: { t: 'On the books with an employer' },
        cash: { t: 'As a contractor or for cash' },
        own: { t: 'Own business' },
        none: { t: 'Not working' },
        dunno: { t: 'I do not know', d: true },
      },
    },
    courts: {
      bn: 'Ties',
      q: {
        self: 'Have you had immigration court dates?',
        other: 'Has he had immigration court dates?',
      },
      hint: 'The history of court appearances is a separate factor in a bond decision.',
      o: {
        came: { t: 'Yes, and came to all of them' },
        missed: { t: 'Yes, with some missed' },
        never: { t: 'There were none' },
        dunno: { t: 'I do not know', d: true },
      },
    },
    sponsor: {
      bn: 'Bond',
      q: {
        self: 'Is there someone nearby with US citizenship or a green card who could post bond for you?',
        other: 'Is there someone nearby with US citizenship or a green card willing to post bond?',
      },
      hint: 'A detained person cannot post their own bond. It can also be posted by a law firm, a nonprofit, or a commercial bondsman — for a non-refundable percentage. The very right to a bond hearing is currently disputed — that is a separate question for the attorney.',
      o: {
        yes: { t: 'Yes, I can name someone' },
        maybe: { t: 'Possibly, I need to talk to them' },
        no: { t: 'There is no such person' },
        dunno: { t: 'I do not know', d: true },
      },
    },
    kids: {
      bn: 'Who depends',
      q: { self: 'Do you have children under 18?', other: 'Does he have children under 18?' },
      hint: 'If there are children, separate tasks appear: school, medical consent, who takes care of them.',
      o: {
        yes: { t: 'Yes' },
        no: { t: 'No' },
        dunno: { t: 'I do not know', d: true },
      },
    },
    school: {
      bn: 'Who depends',
      q: {
        self: 'Is anyone besides you listed at the school?',
        other: 'Is anyone besides him listed at the school?',
      },
      hint: 'If only one adult is on file at the school, the child will not be released to anyone else — not even a grandmother.',
      o: {
        yes: { t: 'Yes, there is a second person' },
        only: { t: 'Only one' },
        dunno: { t: 'I do not know', d: true },
      },
    },
    guard: {
      bn: 'Who depends',
      q: 'Is there an adult ready to take over care of the children?',
      hint: 'It matters that this person has status themselves and is not at risk of detention.',
      o: {
        // min-ok: ключ варианта ответа из прототипа, не поле сбора данных
        status: { t: 'Yes, and they have status' },
        nostatus: { t: 'Yes, but they have no status themselves' },
        no: { t: 'There is no such person' },
        dunno: { t: 'I do not know', d: true },
      },
    },
    dep: {
      bn: 'Who depends',
      q: {
        self: 'Do you care for anyone elderly or ill?',
        other: 'Does he care for anyone elderly or ill?',
      },
      hint: 'Care for the elderly and the ill stops the same day. This is usually forgotten.',
      o: {
        yes: { t: 'Yes' },
        no: { t: 'No' },
        dunno: { t: 'I do not know', d: true },
      },
    },
    meds: {
      bn: 'Health',
      q: { self: 'Do you take regular medication?', other: 'Does he take regular medication?' },
      hint: 'A break in medication inside is a real danger. An exact list with dosages is needed.',
      o: {
        yes: { t: 'Yes' },
        no: { t: 'No' },
        dunno: { t: 'I do not know', d: true },
      },
    },
    hipaa: {
      bn: 'Health',
      q: {
        self: 'Can someone close to you speak with your doctors?',
        other: 'Can someone close to him speak with his doctors?',
      },
      hint: 'If a person is detained, their doctors cannot talk to the family without a signed release form — not even to name the medications or hand over records. Setting it up in advance takes minutes.',
      o: {
        yes: { t: 'Yes, it is in place' },
        no: { t: 'No' },
        dunno: { t: 'I do not know', d: true },
      },
    },
    sole: {
      bn: 'What falls apart',
      q: {
        self: 'Is anything important in your name only: a car, an account, a lease, a business?',
        other: 'Is anything important in his name only: a car, an account, a lease, a business?',
      },
      hint: 'If something is in one person’s name, the others cannot manage it: cannot sell it, cannot pay from it.',
      o: {
        yes: { t: 'Yes, there is' },
        no: { t: 'No, everything is shared' },
        dunno: { t: 'I do not know', d: true },
      },
    },
    pay: {
      bn: 'What falls apart',
      q: {
        self: 'Do you have mandatory regular payments?',
        other: 'Does he have mandatory regular payments?',
      },
      hint: 'Rent, a car loan, insurance, utilities.',
      o: {
        yes: { t: 'Yes' },
        no: { t: 'No' },
        dunno: { t: 'I do not know', d: true },
      },
    },
    trusted: {
      bn: 'What falls apart',
      q: 'Is there a person who knows what to do if you are detained?',
      hint: 'Not "who to call", but who will take action: look for you, call the attorney, pick up the children.',
      o: {
        yes: { t: 'Yes, we have discussed everything' },
        maybe: { t: 'There is a person, but we have not discussed it', d: true },
        no: { t: 'There is no such person' },
        dunno: { t: 'I do not know', d: true },
      },
    },
    phones: {
      bn: 'What falls apart',
      q: {
        self: 'Do you know at least one needed phone number by heart?',
        other: 'Does he know at least one phone number by heart?',
      },
      hint: 'The phone is taken first. Without a memorized number there is no one to call.',
      o: {
        yes: { t: 'Yes' },
        no: { t: 'No' },
      },
    },
    docs: {
      bn: 'Documents',
      q: {
        self: 'Do you have immigration documents and letters from the court?',
        other: 'Does he have immigration documents and letters from the court?',
      },
      hint: 'Those letters contain the A-Number and the case number. It is the fastest way to learn both.',
      o: {
        have: { t: 'I have them on hand' },
        know: { t: 'I know where they are' },
        no: { t: 'No' },
        dunno: { t: 'I do not know', d: true },
      },
    },
    crim: {
      bn: 'Documents',
      q: {
        self: 'Have you had arrests or convictions?',
        other: 'Has he had arrests or convictions?',
      },
      hint: 'If there were any — official court records are needed, not recollections.',
      o: {
        never: { t: 'There were none' },
        docs: { t: 'There were, documents in hand' },
        nodocs: { t: 'There were, no documents' },
        dunno: { t: 'I do not know', d: true },
      },
    },
    copies: {
      bn: 'Documents',
      q: {
        self: 'Does a trusted person keep copies of your documents?',
        other: 'Does a trusted person keep copies of his documents?',
      },
      hint: 'Originals get lost: they stay in the car, in the housing, they leave with the person. Copies are what remains.',
      o: {
        yes: { t: 'Yes' },
        no: { t: 'No' },
        dunno: { t: 'I do not know', d: true },
      },
    },
  },

  tasks: {
    anum_have: {
      h: 'Write the A-Number down separately and photograph it',
      p: 'Everyone will need it: the locator, the attorney, the bond, the court.',
      why: 'The A-Number is the only reliable identifier in the system. Name searches are imprecise: transliteration, name order, typos.',
      how: [
        'Write it on paper and photograph the note',
        'Send it to yourself in a messenger and to a trusted person',
        'Make sure there are nine digits',
      ],
    },
    anum_find: {
      pages: ['anum'],
      h: 'Find the A-Number in documents at home',
      p: 'It is almost certainly in papers you already have.',
      why: 'One old document closes several questions at once: the number, the case number, which court, what happened before.',
      how: [
        'The work permit, even an expired one',
        'The green card, if there is one',
        'Any letter from the immigration court or from USCIS — the agency that issues work permits and green cards',
        'Fee receipts',
        'Photograph every page, including envelopes',
      ],
      src: [
        ['The I-94 entry record — free and immediate', 'i94.cbp.dhs.gov'],
        ['The system search, once the number is found', 'locator.ice.gov'],
      ],
      warn: 'If the ICE site returns Access Denied — turn off the VPN or try another network. The site blocks some addresses; the search is not broken.',
    },
    anum_ask: {
      pages: ['firstcall', 'connect'],
      h: 'Get the A-Number during the first conversation',
      p: 'Ask for it to be dictated one digit at a time.',
      why: 'Without the number, neither the search, nor contacting an attorney, nor bond works.',
      how: [
        'Ask for it slowly and repeat it back aloud',
        'Write it on paper immediately',
        'Also ask for the exact name of the facility and the city',
      ],
      warn: 'The call from the facility is recorded. Saying the A-Number is safe — the agency already has it. Past cases and arrests are not discussed on this line.',
    },
    idb: {
      pages: ['where'],
      h: 'Gather the basic search details',
      p: 'The full name as in the documents, date of birth, country of birth.',
      why: 'Without an A-Number the locator search uses these three fields, and the spelling of the name must match the document.',
      how: [
        'First and last name exactly as in the passport',
        'Date of birth',
        'Country of birth, not of citizenship',
        'Check with relatives if unsure',
      ],
    },
    ev_home: {
      ev: true,
      h: 'Gather proof of a permanent address',
      p: 'The lease, bills, housing documents.',
      why: 'Having a permanent address in the US is on the list of factors a judge considers in a bond decision.',
      how: [
        'The lease or ownership documents',
        'Utility bills for several months',
        'Rent payment receipts: checks, money orders',
        'Letters that arrived at this address',
        'If the lease is in someone else’s name — a letter from the landlord about residence',
      ],
      src: [
        ['The lease and its amendments', 'from the landlord or the management company'],
        ['Monthly bill history', 'the provider’s online account — electricity, water, internet'],
      ],
      say: 'Hello. I am asking you to confirm by letter that I have lived at this address since ___. A free-form letter is enough: who lives here, since what date, your signature and contact. It is needed for documents.',
    },
    ev_years: {
      ev: true,
      h: 'Gather proof of the years lived in the US',
      p: 'The longer the unbroken line, the better.',
      why: 'Length of residence is its own factor on the list. It is proven not with one document but with many small ones. The main rule: any year is closed by any document with the person’s name and a date. You do not need the "right" document — you need at least one for every year.',
      how: [
        'Go year by year, not by document type',
        'For every year — at least one document with a name and a date',
        'Leases, bills, medical and school records',
        'Bank statements and money transfers',
        'Dated photographs, if there is nothing else',
      ],
      src: [
        ['Tax transcripts for every year — free', 'irs.gov/individuals/get-transcript'],
        ['The IRS help line', '800-829-1040'],
        ['The I-94 entry record', 'i94.cbp.dhs.gov'],
      ],
    },
    ev_family: {
      ev: true,
      h: 'Gather documents about family ties',
      p: 'Especially about relatives who are citizens or green card holders.',
      why: 'Family ties are on the list of factors, and judges give particular weight to spouses and children with citizenship or a green card.',
      how: [
        'The children’s birth certificates',
        'The marriage certificate',
        'Copies of relatives’ passports or green cards',
        'Documents showing shared residence',
        'Dated photographs with the children across different years',
      ],
      src: [
        ['Proof of school enrollment', 'the school office, issued at a parent’s request'],
        ['Report cards', 'the school office or the district’s online portal'],
        ['Medical records and the IEP', 'the school’s special education coordinator'],
      ],
    },
    ev_work_off: {
      ev: true,
      h: 'Request proof of employment',
      p: 'A letter, pay stubs, taxes.',
      why: 'Work history is on the list of factors in a bond decision.',
      how: [
        'A letter with the position, tenure, and a note that the job is being held',
        'Pay stubs for several months',
        'W-2 or 1099 for all years',
        'Collect as they come in, do not postpone',
      ],
      src: [
        ['Pay stubs', 'HR or the payroll system — ADP, Paychex'],
        ['Tax transcripts', 'irs.gov/individuals/get-transcript'],
      ],
    },
    ev_work_cash: {
      ev: true,
      h: 'Gather proof of income without an employer letter',
      p: 'Cash work can be documented too.',
      why: 'Not having an official employer does not mean there is no proof — it is gathered from other sources.',
      how: [
        'Transfers and deposits to the account',
        'Correspondence with clients',
        'Receipts, invoices, photos from job sites',
        'Written confirmation from clients',
      ],
      src: [
        ['Transfer history', 'the Remitly, Wise, Western Union app'],
        ['Monthly bank statements', 'the bank’s online account'],
        ['Tax transcripts, if filed', 'irs.gov/individuals/get-transcript'],
        ['The ITIN assignment letter — the number used to pay taxes when there is no SSN', 'from your own document archive'],
      ],
    },
    ev_work_own: {
      ev: true,
      h: 'Gather the documents for your business',
      p: 'Registration, invoices, contracts, taxes.',
      why: 'A business of one’s own proves both employment and ties to the place.',
      how: [
        'Registration documents',
        'Contracts with counterparties',
        'Tax returns',
        'The lease for premises or equipment',
      ],
    },
    ev_courts: {
      ev: true,
      h: 'Gather proof of court appearances',
      p: 'If there were court dates and you came to them — that is in your favor.',
      why: 'The history of court appearances is on the list of factors. The judge looks at whether the person came when summoned.',
      how: [
        'Hearing notices',
        'Appearance records',
        'Any correspondence with the court',
        'The full file of the past case',
      ],
    },
    ev_crim: {
      ev: true,
      h: 'Request court records for all cases',
      p: 'Official documents, not recollections.',
      why: 'Criminal history is on the list of factors, and the attorney needs official disposition records to assess the situation. A retelling from memory does not work.',
      how: [
        'Request a certificate of disposition from the court where the case was',
        'All cases are needed, even old and closed ones',
        'If there are several cases — one for each',
        'If after the case there were programs, courses, volunteering — gather those confirmations too',
        'This takes time, start immediately',
      ],
      warn: 'Do not discuss details on the recorded phone line from the facility. That is a topic for the attorney.',
    },
    lawyer_ready: {
      pages: ['attorney'],
      h: 'Decide in advance which attorney to call',
      p: 'At the moment of detention it is too late to search — the number must already be there.',
      why: 'There is no court-appointed attorney in immigration proceedings. When the contact is chosen in advance, the first day goes into the case, not into searching — and a panicked choice does not lead to a fraudster.',
      how: [
        'Look at both paths: free organizations and paid attorneys — exact addresses below',
        'Collect 2–3 candidates: the practice is federal, you can search by language rather than by city',
        'Check each one against the three registries — it takes three minutes',
        'A consultation in advance is a way to get acquainted and understand the situation before trouble',
        'The chosen attorney’s number goes on the memorized card and to the trusted person',
      ],
      src: [
        ['FREE · the EOIR pro bono list by state', 'justice.gov/eoir/list-pro-bono-legal-service-providers'],
        ['FREE · the directory of free and low-cost help', 'immigrationlawhelp.org'],
        ['FREE · ask a lawyer online', 'americanbar.org/groups/legal_services/flh-home'],
        ['PAID · AILA attorney search with a language filter', 'ailalawyer.com'],
        ['CHECK ANYONE · the EOIR disciplinary list', 'justice.gov/eoir/list-of-currently-disciplined-practitioners'],
      ],
      info: 'How they differ. Free — nonprofit organizations and DOJ accredited representatives: fully legitimate help, but with waiting lists, and not everyone is taken. Paid — an attorney under a written agreement, with a rate or a price per phase, usually available faster. Both are checked against the same registries.',
    },
    community: {
      ev: true,
      h: 'Gather proof of involvement in community life',
      p: 'The parish, organizations, volunteering, the children’s activities.',
      why: 'Community ties are on the list of factors in a bond decision. This dossier grows with time: the earlier it is started, the fuller it is.',
      how: [
        'A letter or confirmation of participation from the parish',
        'Membership in organizations, leagues, clubs',
        'Volunteering — confirmations from the organizations',
        'The children’s activities and clubs: receipts and confirmations',
        'Dated photographs from community events',
      ],
    },
    support_letters: {
      ev: true,
      h: 'Find people for letters of support',
      p: 'The employer, neighbors, the parish, organizations.',
      why: 'Attorneys usually include letters of support in the hearing package: they attest to ties and reputation. Asking at the last moment is too late — people need time to write.',
      how: [
        'Make a list: the employer, a neighbor, a priest, the children’s coach, a coworker',
        'Ask for consent in advance — a person needs several days',
        'A signed letter with the author’s contacts — not an anonymous one',
        'The form and content are determined by the attorney; your part is to find the people and collect contacts',
      ],
      say: 'Hello. Our family will need letters of support for a case. The attorney will explain the form — from you we only need consent and a little time. May I pass your contact to the attorney?',
      warn: 'We do not draft letters to the court. What exactly belongs in a letter is determined by the attorney for the specific case.',
    },
    bond_first: {
      pages: ['bondpay', 'sponsor'],
      h: 'First find out whether there will be a bond hearing at all',
      p: 'The right to one is currently being disputed in the courts.',
      why: 'Since July 2025 the government’s position is that a person who entered the country without inspection is subject to mandatory detention and has no bond. The federal appellate courts split: the Second, Third, Sixth and Eleventh Circuits disagreed; the Fifth and Eighth sided with the government. The Fifth Circuit is Texas, Louisiana and Mississippi — where people are most often transferred. Supreme Court review is expected. Bottom line: the answer depends on where the person is held, and changes with a transfer to another state.',
      how: [
        'Ask the attorney this question first, before anything else',
        'Find out which circuit the facility is in',
        'Ask what changes if the person is transferred to another state',
        'Only then decide whether to look for someone to post the bond',
      ],
      src: [
        ['If there is no attorney yet · free help by state', 'justice.gov/eoir/list-pro-bono-legal-service-providers'],
        ['The directory of free and low-cost help', 'immigrationlawhelp.org'],
        ['Paid search with a language filter', 'ailalawyer.com'],
      ],
      warn: 'Only an attorney can determine whether this applies to a specific person. This describes the state of the dispute as of July 2026 — it moves fast, check the date.',
    },
    sponsor_ready: {
      pages: ['sponsor'],
      h: 'Prepare the documents of the person who will post the bond',
      p: 'They will need proof of status.',
      why: 'Bond can be posted by a US citizen or green card holder 18 or older, and also by law firms and nonprofit organizations.',
      how: [
        'A US passport, birth certificate, or green card',
        'The same spelling of their details on the document, the bank account, and the profile',
        'Readiness to pay by wire transfer',
        'Warn them: the attorney may also ask them for a letter of support',
      ],
    },
    sponsor_talk: {
      pages: ['sponsor'],
      h: 'Talk in advance to the person who could post the bond',
      p: 'It is a hard conversation; better not to start it on the day of the hearing.',
      why: 'There are usually only a few people with the right status around, and the request is serious — so it gets postponed until the last moment. The conversation is easier when you show both paths: the full amount posted personally — returned at the end of the case, or through a bondsman — only a percentage is paid, but it is not refunded.',
      how: [
        'Explain that the money comes back at the end of the case',
        'Say honestly: it can take years',
        'If the full amount is too much, tell them about the second path: a bondsman posts the bond for a non-refundable percentage',
        'Warn that their documents will be needed',
        'Give them time to think',
      ],
      say: 'I need to ask something serious. For a person to be released, the bond must be posted by a citizen or green card holder — I cannot do it myself. The money is returned after the case ends, but that can take a long time. If the full amount is too much, there is a path through a bond company: then only a percentage is paid, but it is not refunded. I will understand any answer. May I explain how it works?',
      warn: 'Do not promise refund timing — it depends on neither of you.',
    },
    bondfund: {
      pages: ['sponsor'],
      h: 'Look at bond funds and bondsmen',
      p: 'An organization can post the bond, not only someone close.',
      why: 'If there is no suitable person, there are two paths without one: a nonprofit bond fund — or a commercial bondsman, who posts the bond for a non-refundable percentage of the amount. For many people these are the only options.',
      how: [
        'Look for funds working in this state',
        'Ask whether they take this facility',
        'Ask about the waiting list and the conditions',
        'A bondsman is the second path: a percentage is paid and not refunded; every company has its own requirements — compare terms in writing',
        'Check the organization against the same registries as an attorney',
      ],
      warn: 'The set of funds changes; some close. Make sure the organization is operating now.',
    },
    school_add: {
      h: 'Add a second person at the school',
      p: 'Right now only one adult is allowed to pick the child up.',
      why: 'The school releases a child only to those on its card. It is done with a form at the office and needs no court.',
      how: [
        'Come to the school office in person',
        'Ask for the authorized pickup or emergency contact form',
        'Bring photo identification',
        'Ask for a copy of the completed form for yourself',
        'Separately note who the child must not be released to',
      ],
      say: 'Hello. I want to add a person to the list of those who may pick up the child, and update the emergency contacts. Could you tell me which form to fill out?',
    },
    caregiver: {
      h: 'Set up the caregiving document for the children',
      p: 'A relative gets the ability to take them to school and the doctor without court.',
      why: 'In California, the Caregiver’s Authorization Affidavit lets a relative enroll the child in school and consent to medical care. Court guardianship is not needed.',
      form: 'This is a form established by law. We do not draft it — use the official blank. It does not take away parental rights.',
      warn: 'Outside California the procedure is different. Check the rules of the state.',
    },
    caregiver_risk: {
      h: 'Find an adult with status for the children',
      p: 'The caregiver must not be at risk of detention themselves.',
      why: 'If the person assigned to care for the children has no status themselves, the plan can collapse the same day. Organizations advise choosing a citizen or green card holder.',
      how: [
        'Make a list of suitable adults',
        'Talk in advance, do not present it as a fait accompli',
        'Make sure they know where the documents are',
        'Have them memorize the needed phone numbers',
      ],
    },
    dep_plan: {
      h: 'Think through who will care for dependents',
      p: 'The elderly and the ill are left without care the same day.',
      why: 'Preparation plans are usually built around children, and dependent adults fall through. Care stops immediately.',
      how: [
        'Who comes and how often',
        'Where the medications and prescriptions are',
        'Who can speak with the doctors',
        'Who pays and with what',
      ],
    },
    meds_list: {
      h: 'Make a list of medications',
      p: 'Names and dosages, not "blood pressure pills".',
      why: 'In the facility the medications must be named exactly. A break in taking them is a real health risk.',
      how: [
        'Full names and dosages',
        'The treating doctors’ contacts',
        'Diagnoses, if there are documents',
        'Ask the doctor for copies of the medical records — they are useful for the case too',
        'Carry a copy and leave one with a trusted person',
      ],
    },
    hipaa: {
      h: 'Set up access to medical information',
      p: 'Without it a relative cannot speak with the doctors.',
      why: 'A HIPAA form is a paper by which a person allows doctors to discuss their health with whoever is named in it. With it signed, a trusted person can get medical records and talk to the doctors. It is needed both for health and as evidence for the case.',
      form: 'The blank comes from the medical facility; the form is standard. We do not draft it. The form for the hospital and the consent for the agency to share information are different papers.',
    },
    poa: {
      h: 'Sort out the power of attorney',
      p: 'One document covers the car, the account and the contracts.',
      why: 'Property in one person’s name becomes inaccessible to everyone else. The car cannot be sold, the account cannot be managed, the contract cannot be reassigned.',
      form: 'A power of attorney is a legal document. We do not draft it and we do not provide samples. The usual procedure: take the state’s official form or the bank’s own form, fill it in, and have the signature certified — in California before a notary or with two witnesses. A US notary certifies the signature; they do not draft the document. If the person is already detained — the signing procedure is different; that is a question for the attorney.',
      how: [
        'Define what exactly needs to be covered',
        'Check whether the bank or agency requires its own form',
        'Make copies and say where the original is',
      ],
    },
    payments: {
      h: 'Make a list of mandatory payments',
      p: 'With dates and amounts. Someone has to cover them.',
      why: 'Delinquencies start silently: rent, the car loan, insurance. Within weeks the car is towed and the housing is lost.',
      how: [
        'Write out all regular payments with dates',
        'Note where they are charged from',
        'Note who has access to that money',
        'Start with the nearest date',
      ],
    },
    phones: {
      pages: ['firstcall'],
      h: 'Memorize two phone numbers',
      p: 'The phone is taken first.',
      why: 'Help organizations put this among the first steps: without a memorized number a person in the facility cannot call anyone, even when a call is allowed.',
      how: [
        'One number of a close person',
        'The second — an attorney or an organization',
        'Check that you remember them without a prompt',
        'Also write them on paper kept separately from the phone',
      ],
    },
    docs_gather: {
      h: 'Gather the documents into one folder',
      p: 'And make copies.',
      why: 'Originals get lost: they stay in the car, in the housing, they leave with the person.',
      how: [
        'Passports, birth and marriage certificates',
        'All immigration documents and letters',
        'Medical and school records',
        'Photograph everything, including the backs',
      ],
    },
    copies_trusted: {
      h: 'Give copies to a trusted person',
      p: 'Keep the originals separately.',
      why: 'Organizations advise keeping copies where a reliable person can reach them if you are not there.',
      how: [
        'Choose a person who is not at risk themselves',
        'Hand over the copies and say where the originals are',
        'Duplicate to the cloud',
      ],
      warn: 'The plan and documents are not carried around. Keep them in a safe place, and tell only trusted people where.',
    },
    trusted_setup: {
      h: 'Make the arrangement with your trusted person',
      p: 'Not "who to call", but who will take action.',
      why: 'Gathered papers are worth nothing if no one knows they exist and where they are. Detention happens suddenly, and from then on it is not the person taken who acts, but the one who remains.',
      how: [
        'Choose a person who is not at risk of detention themselves',
        'Show them where the documents and copies are',
        'Have them memorize your A-Number',
        'Agree on who they call first',
        'Say who picks up the children and who knows about the medications',
      ],
      say: 'I want to ask you something, just in case. If something happens to me and I stop being in touch — here is where my documents are, here is who to call. I hope it will not be needed. May I show you?',
      warn: 'Do not carry the plan and documents around. Keep them in a reliable place, and only trusted people know where.',
    },
    trusted_find: {
      h: 'Find the person who will act',
      p: 'Until there is one, all the preparation rests on you alone.',
      why: 'If no one knows about your situation, nothing will happen in the first day after a detention: no one will look for you, no one will get the documents, no one will pick up the children.',
      how: [
        'A coworker, a neighbor, someone from the community or the parish will do',
        'Not necessarily a relative and not necessarily a close friend',
        'What matters is that they agree and are not at risk themselves',
        'One person is enough, but two are better',
      ],
    },
    court_dates: {
      pages: ['deadlines'],
      h: 'Keep the hearing dates under control',
      p: 'A missed hearing is the most common irreversible loss.',
      why: 'If a person does not come to a scheduled hearing, the case can be decided without him, in absentia. Most often this happens not because of flight but because of a move: the notice goes to the old address.',
      how: [
        'Check your hearing date in the official system',
        'Set reminders 14, 3, and 1 day ahead',
        'After a move, file the change of address with the court on separate form EOIR-33',
        'Keep the proof of filing',
      ],
      src: [
        ['Checking the hearing date', 'acis.eoir.justice.gov'],
        ['The change of address form', 'justice.gov/eoir/form-eoir-33'],
      ],
    },
    prior_case: {
      h: 'Retrieve the documents of the past case',
      p: 'What happened before determines a great deal.',
      why: 'A past detention or a closed case leaves a trace in the system, and the attorney needs documents, not recollections. It is the first thing they will ask about.',
      how: [
        'All notices and decisions from the past case',
        'The past case number, if it survived',
        'If there are no papers — a request to the court or through the attorney',
        'Photograph everything you find',
      ],
      warn: 'Do not discuss past cases on the recorded phone line from the facility. That is a topic for the attorney.',
    },
    connect: {
      pages: ['connect'],
      h: 'Set up contact and money for calls',
      p: 'Two ways to pay, and the difference in cost is significant.',
      why: 'You cannot call in — only he calls out. While there is no money on the account, there is no contact at all. Regular warm contact is what protects a person inside more than anything else.',
      how: [
        'Find out which phone carrier this facility uses',
        'Option 1: top up the detained person’s own balance — he calls whoever he wants',
        'Option 2: link an account to your number — calls only to you, usually cheaper per the carrier’s rates',
        'Put the A-Number on everything you send',
      ],
      src: [
        ['The carriers’ apps', 'GettingOut · Securus · ConnectNetwork'],
        ['Letters and postcards to facilities', 'pigeon.ly'],
      ],
      form: 'Important about topping up: you cannot add money in the GettingOut app — the app shows the balance and messages, but payment does not work in it. Top up through the carrier’s website in a browser, from a computer or a phone. Other carriers can be the same — if the app has no payment button, look for the website, do not reinstall the app.',
      warn: 'Books — new only and directly from a store or publisher, not from a private person. Softcover clears faster: hardcovers take longer to screen and are often refused. Every facility has its own rules — confirm by phone before sending.',
    },
    money: {
      pages: ['state-ca'],
      h: 'See where families find the money',
      p: 'Bond, attorney, rent — the costs arrive together. Mechanisms exist.',
      why: 'Fundraisers through GoFundMe and mutual-aid networks are a recognized mechanism: families raise tens of thousands of dollars for bond and attorneys. Asking for help publicly is normal here — hundreds of families do it.',
      how: [
        'A fundraiser (GoFundMe and similar): describe the situation honestly, with the goal and the amount — bond, attorney, rent',
        'Ask the parish, an organization, coworkers to share it — fundraisers work through trust, not through strangers',
        'Mutual-aid networks at communities and churches — ask in yours',
        'Bond funds — on the state page',
        'Keep a record of what was raised and spent: donors’ trust is the fundraiser’s main resource',
      ],
      warn: 'We do not give financial advice and we do not collect money. Check who you send money to: the fundraiser should be run by a person you know personally.',
    },
    support: {
      h: 'Share the load and stay close to people',
      p: 'Fear and sleeplessness here are a normal reaction.',
      why: 'Cases run for months. A person who carries everything alone burns out before the process ends. The app is a tool, not a substitute for human support.',
      how: [
        'Distribute tasks among family, do not take everything on yourself',
        'Keep your usual routines: sleep, food, work',
        'Lean on the living people around you',
      ],
      src: [
        ['The crisis line, around the clock and free', '988 — call or text'],
        ['Crisis Text Line', 'text HOME to 741741'],
        ['In immediate danger', '911'],
      ],
      warn: 'This is general reference information, not medical or psychological help.',
    },
    nosign: {
      pages: ['documents'],
      h: 'Sign nothing without an attorney',
      p: 'Some documents mean giving up the court case.',
      why: 'Voluntary departure and stipulated removal mean agreeing to leave and giving up the hearing. After signing, the case never reaches a judge.',
      how: [
        'Pass this on in the very first conversation',
        'The wording is simple: I am not signing anything without an attorney',
        'Ask whether he has already signed anything, and what exactly',
      ],
      warn: 'ACLU, FIRRP and ILRC publish the recommendation not to sign documents before speaking with an attorney and to give only your name.',
    },
    verify: {
      pages: ['verify'],
      h: 'Check who you are paying before you pay',
      p: 'Three government registries, three minutes.',
      why: 'In the US a notary is not a lawyer and cannot represent anyone in immigration court. In Latin America a notario público is a lawyer. The most common fraud is built on that difference.',
      how: [
        'The state bar — an active license',
        'The DOJ accredited representatives roster',
        'The EOIR disciplinary list',
      ],
      src: [
        ['The EOIR disciplinary list', 'justice.gov/eoir/list-of-currently-disciplined-practitioners'],
        ['Attorney search with a language filter', 'ailalawyer.com'],
      ],
      // upl-ok: описание признаков обмана, не наше обещание и не оценка
      warn: 'Red flags: a promise of release on a specific day, a guarantee of the outcome, cash up front with no agreement, refusing to give a license number.',
    },
    freehelp: {
      pages: ['attorney'],
      h: 'Look for a free legal consultation',
      p: 'Nonprofit organizations run free screenings.',
      why: 'Organizations maintain national directories of free and low-cost immigration help. A screening helps understand which options exist at all.',
      how: [
        'Call several at once — there are queues everywhere',
        'Ask whether they take detained cases',
        'Check whether they work with this facility',
      ],
      src: [
        ['The EOIR pro bono list by state', 'justice.gov/eoir/list-pro-bono-legal-service-providers'],
        ['The directory of free and low-cost help', 'immigrationlawhelp.org'],
        ['Free answers from lawyers', 'americanbar.org/groups/legal_services/flh-home'],
      ],
      warn: 'There is no court-appointed attorney in immigration proceedings. Free help exists, but with queues.',
    },
  },

  reasons: {
    anum_have: 'the number is known',
    anum_find_docs: 'there are documents at home',
    anum_none: 'there is no number',
    idb: 'not enough details for the search',
    urgent: 'the person has already been detained',
    money: 'the costs arrive together — bond, attorney, rent',
    freehelp: 'a legal assessment is needed',
    support: 'the case runs long',
    trusted_yes: 'there is a trusted person',
    trusted_maybe: 'there is no arrangement',
    trusted_no: 'there is no one to act for you',
    case_open: 'the court case is ongoing',
    prior: 'detained before',
    home_has: 'there is a housing agreement',
    home_none: 'no lease — other proof of address is needed',
    years: 'length of residence',
    family: 'there are relatives with status',
    community: 'community ties are part of the dossier',
    support_letters: 'letters are usually requested for the hearing',
    work_off: 'official employment',
    work_cash: 'cash work',
    work_own: 'own business',
    courts: 'there were court dates',
    crim: 'there were arrests',
    bond_first: 'the right to bond is currently disputed',
    lawyer_ready: 'an attorney is found before detention, not after',
    sponsor_yes: 'there is someone to post the bond',
    sponsor_maybe: 'who posts the bond is still open',
    sponsor_no: 'there is no suitable person',
    school_only: 'only one adult is listed at the school',
    guard_status: 'there is an adult with status',
    guard_risk: 'the caregiver is at risk or absent',
    dep: 'there are dependents besides children',
    meds: 'takes medication',
    hipaa: 'doctor access is not set up',
    sole: 'property is in one person’s name',
    pay: 'there are regular payments',
    phones: 'the numbers are not memorized',
    docs_has: 'the documents exist',
    docs_none: 'the documents cannot be found',
    copies: 'the trusted person has no copies',
  },
}

export default c
