import type { IntakeContent } from '@/lib/types'

// Traducido del original ruso (content/intake/ru.ts). La redacción está
// calibrada para la prohibición de práctica legal sin licencia — no reescribir.
// Antes de publicar, el español lo revisa un hablante nativo de la comunidad.

const c: IntakeContent = {
  ui: {
    done: 'listo',
    reassure: 'Si no sabe — dígalo así. Es una respuesta normal, y también se convierte en una tarea.',
    backBtn: 'Atrás',
    nextBtn: 'Siguiente',
    resultEyebrow: 'Su lista',
    resultTitle: 'tareas',
    resultHint:
      'Armada con sus respuestas. Nada se fue a nuestro servidor — la lista vive solo en este navegador. Toque una tarea para abrirla.',
    resultIntro:
      'No se preocupe: con todo esto se puede, y no en un solo día. Vaya paso a paso desde arriba — dentro de cada tarea dice para qué es, cómo hacerla y dónde conseguir las cosas. Muchas tareas tienen enlace a una página con la instrucción completa. Guarde o imprima la lista para que no se pierda.',
    moreLabel: 'Instrucción completa',
    groups: { now: 'Ahora', soon: 'Esta semana', later: 'Cuando haya tiempo' },
    whyPrefix: 'por qué está en la lista',
    sections: {
      why: 'Para qué',
      how: 'Cómo',
      src: 'Dónde conseguirlo exactamente',
      info: 'Referencia',
      say: 'Qué decir',
      sayTag: 'EJEMPLO · AJÚSTELO A SUS PALABRAS',
      form: 'Formulario',
      warn: 'Atención',
    },
    evBadge: 'PRUEBA',
    evNote: {
      h: 'Sobre la etiqueta «prueba»',
      p: 'Así se marcan las tareas de la lista de factores que se consideran al decidir sobre la fianza: dirección, tiempo de residencia, lazos familiares, trabajo, asistencia a la corte, antecedentes. La lista viene de una decisión publicada de la BIA — la corte de inmigración más alta para apelaciones, cuyas decisiones siguen todos los jueces de inmigración. No evaluamos su situación y no predecimos el resultado — solo enumeramos lo que normalmente se respalda con documentos.',
    },
    zoneBNote: {
      h: 'Qué hacer con esta lista ahora',
      p: 'Descárguela o imprímala — es el borrador del paquete para el abogado. Los abogados cobran por minutos: una familia que llega con la lista ordenada y los documentos paga por el trabajo en el caso, no por ordenar papeles. Prepare también las respuestas a las preguntas que el abogado hará primero: año y forma de entrada, casos y órdenes anteriores, detenciones anteriores. Aquí no se preguntan y no se muestran en pantalla — esa conversación es solo con el abogado.',
    },
    printBtn: 'Guardar o imprimir',
    againBtn: 'Empezar de nuevo',
    foot: 'No somos abogados y no damos asesoría legal. Esto es una lista de tareas, no una posición legal. Los ejemplos son correspondencia cotidiana; no redactamos documentos legales.',
  },

  questions: {
    role: {
      bn: 'Marco',
      q: '¿Está llenando esto por usted o por otra persona?',
      hint: 'Las listas salen distintas. Por usted — es preparación para el futuro; por otro — qué hacer ahora mismo.',
      o: {
        self: { t: 'Por mí', s: 'Quiero prepararme con tiempo' },
        other: { t: 'Por otra persona', s: 'Lo detuvieron o es posible' },
      },
    },
    state: {
      bn: 'Marco',
      q: { self: '¿Cuál es su situación?', other: '¿Qué pasó?' },
      hint: 'De esto depende qué va primero en la lista: pasos urgentes o preparación con calma.',
      o: {
        nothing: { t: { self: 'Todo tranquilo — me preparo con tiempo', other: 'Por ahora no ha pasado nada' } },
        case: { t: 'Hay un caso abierto en la corte' },
        before: { t: 'Lo detuvieron antes, ahora está libre' },
        just: { t: 'Lo detuvieron hoy o ayer' },
        found: { t: 'Ya lo encontramos en el sistema' },
        court: { t: 'Ya hubo una audiencia' },
      },
    },
    anum: {
      bn: 'Identificación',
      q: { self: '¿Sabe su número A?', other: '¿Se conoce su número A?' },
      hint: 'La letra A y nueve dígitos. Está en el permiso de trabajo, la green card, las cartas de la corte y de USCIS — la agencia que da los permisos de trabajo y las green cards.',
      o: {
        yes: { t: 'Sí, lo sé' },
        find: { t: 'No, pero hay documentos en casa' },
        no: { t: 'No, y no hay documentos' },
        what: { t: 'No sé qué es eso', d: true },
      },
    },
    idb: {
      bn: 'Identificación',
      q: '¿Sabe su nombre completo, fecha de nacimiento y país de nacimiento?',
      hint: 'Si no se conoce el número A, la búsqueda usa estos tres campos. La escritura del nombre debe coincidir con el documento.',
      o: {
        all: { t: 'Lo sé todo' },
        part: { t: 'Sé una parte' },
        no: { t: 'Casi nada', d: true },
      },
    },
    years: {
      bn: 'Lazos',
      q: { self: '¿Cuántos años lleva en EE. UU.?', other: '¿Cuántos años lleva él en EE. UU.?' },
      hint: 'El tiempo de residencia es uno de los factores que el juez considera al decidir sobre la fianza.',
      o: {
        lt1: { t: 'Menos de un año' },
        '1_5': { t: 'De uno a cinco' },
        '5_10': { t: 'De cinco a diez' },
        gt10: { t: 'Más de diez' },
        dunno: { t: 'No sé', d: true },
      },
    },
    home: {
      bn: 'Lazos',
      q: {
        self: '¿El contrato de renta o la propiedad están a su nombre?',
        other: '¿A nombre de quién está la vivienda?',
      },
      hint: 'El contrato de renta y los recibos muestran que la persona tiene vivienda permanente. Es una de las cosas que mira el juez al decidir sobre la fianza.',
      o: {
        me: { t: { self: 'Sí, a mi nombre', other: 'Al mío' } },
        him: { t: 'Al suyo' },
        both: { t: 'De los dos' },
        other: { t: 'No, de otra persona' },
        none: { t: 'No hay contrato' },
        dunno: { t: 'No sé', d: true },
      },
    },
    usfam: {
      bn: 'Lazos',
      q: {
        self: '¿Tiene en EE. UU. familiares cercanos con ciudadanía o green card?',
        other: '¿Tiene él en EE. UU. familiares cercanos con ciudadanía o green card?',
      },
      hint: 'Los jueces dan un peso especial a cónyuges e hijos que son ciudadanos o titulares de green card.',
      o: {
        close: { t: 'Sí, cónyuge o hijos' },
        other: { t: 'Sí, otros familiares' },
        no: { t: 'No' },
        dunno: { t: 'No sé', d: true },
      },
    },
    work: {
      bn: 'Lazos',
      q: { self: '¿Cómo está el trabajo para usted?', other: '¿Cómo está el trabajo para él?' },
      hint: 'El trabajo también es prueba de lazos. Le indicaremos exactamente con qué respaldarlo.',
      o: {
        official: { t: 'Formal, con un empleador' },
        cash: { t: 'Como contratista o en efectivo' },
        own: { t: 'Negocio propio' },
        none: { t: 'No trabaja' },
        dunno: { t: 'No sé', d: true },
      },
    },
    courts: {
      bn: 'Lazos',
      q: {
        self: '¿Ha tenido citas en la corte de inmigración?',
        other: '¿Ha tenido él citas en la corte de inmigración?',
      },
      hint: 'La historia de asistencia a la corte es un factor aparte al decidir sobre la fianza.',
      o: {
        came: { t: 'Sí, y fue a todas' },
        missed: { t: 'Sí, con algunas faltas' },
        never: { t: 'No hubo' },
        dunno: { t: 'No sé', d: true },
      },
    },
    sponsor: {
      bn: 'Fianza',
      q: {
        self: '¿Hay cerca una persona con ciudadanía de EE. UU. o green card que pudiera pagar la fianza por usted?',
        other: '¿Hay cerca una persona con ciudadanía de EE. UU. o green card dispuesta a pagar la fianza?',
      },
      hint: 'El detenido no puede pagar su propia fianza. También pueden pagarla un bufete, una organización sin fines de lucro o una compañía de fianzas — por un porcentaje que no se devuelve. El propio derecho a la audiencia de fianza está en disputa — esa es una pregunta aparte para el abogado.',
      o: {
        yes: { t: 'Sí, tengo a quién nombrar' },
        maybe: { t: 'Puede ser, hay que hablar' },
        no: { t: 'No hay personas así' },
        dunno: { t: 'No sé', d: true },
      },
    },
    kids: {
      bn: 'Quién depende',
      q: { self: '¿Tiene hijos menores de 18?', other: '¿Tiene él hijos menores de 18?' },
      hint: 'Si hay hijos, aparecen tareas aparte: la escuela, el consentimiento médico, quién los cuida.',
      o: {
        yes: { t: 'Sí' },
        no: { t: 'No' },
        dunno: { t: 'No sé', d: true },
      },
    },
    school: {
      bn: 'Quién depende',
      q: {
        self: '¿Figura en la escuela alguien más aparte de usted?',
        other: '¿Figura en la escuela alguien más aparte de él?',
      },
      hint: 'Si en la escuela hay un solo adulto registrado, no entregarán al niño a nadie más — ni siquiera a la abuela.',
      o: {
        yes: { t: 'Sí, hay una segunda persona' },
        only: { t: 'Solo uno' },
        dunno: { t: 'No sé', d: true },
      },
    },
    guard: {
      bn: 'Quién depende',
      q: '¿Hay un adulto dispuesto a hacerse cargo de los niños?',
      hint: 'Importa que esa persona tenga estatus y no esté ella misma en riesgo de detención.',
      o: {
        // min-ok: ключ варианта ответа из прототипа, не поле сбора данных
        status: { t: 'Sí, y tiene estatus' },
        nostatus: { t: 'Sí, pero no tiene estatus' },
        no: { t: 'No hay una persona así' },
        dunno: { t: 'No sé', d: true },
      },
    },
    dep: {
      bn: 'Quién depende',
      q: {
        self: '¿Cuida usted a personas mayores o enfermas?',
        other: '¿Cuida él a personas mayores o enfermas?',
      },
      hint: 'El cuidado de mayores y enfermos se corta el mismo día. Esto normalmente se olvida.',
      o: {
        yes: { t: 'Sí' },
        no: { t: 'No' },
        dunno: { t: 'No sé', d: true },
      },
    },
    meds: {
      bn: 'Salud',
      q: {
        self: '¿Toma medicamentos de forma permanente?',
        other: '¿Toma él medicamentos de forma permanente?',
      },
      hint: 'Una pausa en los medicamentos adentro es un peligro real. Hace falta una lista exacta con dosis.',
      o: {
        yes: { t: 'Sí' },
        no: { t: 'No' },
        dunno: { t: 'No sé', d: true },
      },
    },
    hipaa: {
      bn: 'Salud',
      q: {
        self: '¿Puede alguien cercano hablar con sus médicos?',
        other: '¿Puede alguien cercano hablar con sus médicos?',
      },
      hint: 'Si detienen a la persona, sus médicos no pueden hablar con los suyos sin un formulario firmado — ni decir los medicamentos ni entregar los registros. Arreglarlo con tiempo toma unos minutos.',
      o: {
        yes: { t: 'Sí, está arreglado' },
        no: { t: 'No' },
        dunno: { t: 'No sé', d: true },
      },
    },
    sole: {
      bn: 'Qué se desarma',
      q: {
        self: '¿Hay algo importante solo a su nombre: el carro, la cuenta, la renta, el negocio?',
        other: '¿Hay algo importante solo a nombre de él: el carro, la cuenta, la renta, el negocio?',
      },
      hint: 'Si algo está a nombre de una sola persona, los demás no pueden disponer de ello: ni venderlo, ni pagar desde ahí.',
      o: {
        yes: { t: 'Sí, hay' },
        no: { t: 'No, todo es compartido' },
        dunno: { t: 'No sé', d: true },
      },
    },
    pay: {
      bn: 'Qué se desarma',
      q: {
        self: '¿Tiene pagos regulares obligatorios?',
        other: '¿Tiene él pagos regulares obligatorios?',
      },
      hint: 'La renta, el préstamo del carro, el seguro, los servicios.',
      o: {
        yes: { t: 'Sí' },
        no: { t: 'No' },
        dunno: { t: 'No sé', d: true },
      },
    },
    trusted: {
      bn: 'Qué se desarma',
      q: '¿Hay una persona que sepa qué hacer si lo detienen a usted?',
      hint: 'No «a quién llamar», sino quién va a actuar: buscarlo, llamar al abogado, recoger a los niños.',
      o: {
        yes: { t: 'Sí, lo hablamos todo' },
        maybe: { t: 'Hay una persona, pero no lo hemos hablado', d: true },
        no: { t: 'No hay una persona así' },
        dunno: { t: 'No sé', d: true },
      },
    },
    phones: {
      bn: 'Qué se desarma',
      q: {
        self: '¿Se sabe de memoria al menos un número de teléfono necesario?',
        other: '¿Se sabe él de memoria al menos un número de teléfono?',
      },
      hint: 'El teléfono es lo primero que quitan. Sin un número aprendido no hay a quién llamar.',
      o: {
        yes: { t: 'Sí' },
        no: { t: 'No' },
      },
    },
    docs: {
      bn: 'Documentos',
      q: {
        self: '¿Tiene documentos de inmigración y cartas de la corte?',
        other: '¿Tiene él documentos de inmigración y cartas de la corte?',
      },
      hint: 'En esas cartas están el número A y el número del caso. Es la forma más rápida de saber los dos.',
      o: {
        have: { t: 'Los tengo a la mano' },
        know: { t: 'Sé dónde están' },
        no: { t: 'No' },
        dunno: { t: 'No sé', d: true },
      },
    },
    crim: {
      bn: 'Documentos',
      q: {
        self: '¿Ha tenido arrestos o condenas?',
        other: '¿Ha tenido él arrestos o condenas?',
      },
      hint: 'Si los hubo — hacen falta constancias oficiales de la corte, no recuerdos.',
      o: {
        never: { t: 'No hubo' },
        docs: { t: 'Hubo, con documentos' },
        nodocs: { t: 'Hubo, sin documentos' },
        dunno: { t: 'No sé', d: true },
      },
    },
    copies: {
      bn: 'Documentos',
      q: {
        self: '¿Una persona de confianza guarda copias de sus documentos?',
        other: '¿Una persona de confianza guarda copias de sus documentos?',
      },
      hint: 'Los originales se pierden: quedan en el carro, en la vivienda, se van con la persona. Las copias son lo que queda.',
      o: {
        yes: { t: 'Sí' },
        no: { t: 'No' },
        dunno: { t: 'No sé', d: true },
      },
    },
  },

  tasks: {
    anum_have: {
      h: 'Anote el número A aparte y fotografíelo',
      p: 'Lo van a necesitar todos: el localizador, el abogado, la fianza, la corte.',
      why: 'El número A es el único identificador confiable en el sistema. La búsqueda por nombre es imprecisa: transliteración, orden de los nombres, errores de tipeo.',
      how: [
        'Escríbalo en papel y fotografíe la nota',
        'Envíeselo a usted mismo por mensajería y a una persona de confianza',
        'Verifique que sean nueve dígitos',
      ],
    },
    anum_find: {
      pages: ['anum'],
      h: 'Busque el número A en los documentos de casa',
      p: 'Casi seguro está en papeles que ya tiene.',
      why: 'Un documento viejo cierra varias preguntas a la vez: el número, el número del caso, qué corte, qué pasó antes.',
      how: [
        'El permiso de trabajo, aunque esté vencido',
        'La green card, si hay',
        'Cualquier carta de la corte de inmigración o de USCIS — la agencia que da los permisos de trabajo y las green cards',
        'Recibos de pago de cuotas',
        'Fotografíe todas las páginas, incluidos los sobres',
      ],
      src: [
        ['El registro de entrada I-94 — gratis y al momento', 'i94.cbp.dhs.gov'],
        ['La búsqueda en el sistema, cuando tenga el número', 'locator.ice.gov'],
      ],
      warn: 'Si el sitio de ICE da Access Denied — apague el VPN o pruebe otra red. El sitio bloquea algunas direcciones; la búsqueda no está rota.',
    },
    anum_ask: {
      pages: ['firstcall', 'connect'],
      h: 'Consiga el número A en la primera conversación',
      p: 'Pida que lo dicten dígito por dígito.',
      why: 'Sin el número no funciona ni la búsqueda, ni el contacto con el abogado, ni la fianza.',
      how: [
        'Pida que lo dicten despacio y repítalo en voz alta',
        'Anótelo en papel de inmediato',
        'Pregunte también el nombre exacto del centro y la ciudad',
      ],
      warn: 'La llamada desde el centro se graba. Decir el número A es seguro — la agencia ya lo tiene. Los casos y arrestos anteriores no se hablan por esta línea.',
    },
    idb: {
      pages: ['where'],
      h: 'Reúna los datos básicos para la búsqueda',
      p: 'El nombre completo como en los documentos, fecha de nacimiento, país de nacimiento.',
      why: 'Sin número A la búsqueda en el localizador usa estos tres campos, y la escritura del nombre debe coincidir con el documento.',
      how: [
        'Nombre y apellido exactamente como en el pasaporte',
        'Fecha de nacimiento',
        'País de nacimiento, no de ciudadanía',
        'Confirme con los familiares si tiene dudas',
      ],
    },
    ev_home: {
      ev: true,
      h: 'Reúna la prueba de dirección permanente',
      p: 'El contrato de renta, los recibos, los documentos de la vivienda.',
      why: 'Tener una dirección permanente en EE. UU. está en la lista de factores que el juez considera al decidir sobre la fianza.',
      how: [
        'El contrato de renta o los documentos de propiedad',
        'Recibos de servicios de varios meses',
        'Comprobantes de pago de la vivienda: cheques, money orders',
        'Cartas que llegaron a esta dirección',
        'Si el contrato está a nombre de otro — una carta del arrendador sobre la residencia',
      ],
      src: [
        ['El contrato de renta y sus anexos', 'con el arrendador o la administración'],
        ['El historial de recibos por mes', 'la cuenta del proveedor — luz, agua, internet'],
      ],
      say: 'Buenos días. Le pido que confirme por carta que vivo en esta dirección desde ___. Basta un formato libre: quién vive, desde qué fecha, su firma y contacto. Es para unos documentos.',
    },
    ev_years: {
      ev: true,
      h: 'Reúna las pruebas de los años vividos en EE. UU.',
      p: 'Cuanto más larga la línea continua, mejor.',
      why: 'El tiempo de residencia es un factor propio de la lista. No se prueba con un documento sino con muchos pequeños. La regla principal: cualquier año se cierra con cualquier documento que tenga el nombre de la persona y una fecha. No hace falta el documento «correcto» — hace falta al menos uno por cada año.',
      how: [
        'Vaya por años, no por tipos de documento',
        'Por cada año — al menos un documento con nombre y fecha',
        'Contratos de renta, recibos, registros médicos y escolares',
        'Estados de cuenta y transferencias',
        'Fotos con fecha, si no hay nada más',
      ],
      src: [
        ['Transcripciones de impuestos de cada año — gratis', 'irs.gov/individuals/get-transcript'],
        ['La línea de ayuda del IRS', '800-829-1040'],
        ['El registro de entrada I-94', 'i94.cbp.dhs.gov'],
      ],
    },
    ev_family: {
      ev: true,
      h: 'Reúna los documentos de los lazos familiares',
      p: 'Sobre todo de familiares ciudadanos y titulares de green card.',
      why: 'Los lazos familiares están en la lista de factores, y los jueces dan un peso especial a cónyuges e hijos con ciudadanía o green card.',
      how: [
        'Actas de nacimiento de los hijos',
        'Acta de matrimonio',
        'Copias de pasaportes o green cards de los familiares',
        'Documentos de residencia compartida',
        'Fotos con fecha con los hijos a lo largo de los años',
      ],
      src: [
        ['Constancia de inscripción escolar', 'la oficina de la escuela, la dan a pedido del padre o la madre'],
        ['Boletas de calificaciones', 'la oficina de la escuela o el portal del distrito'],
        ['Registros médicos y el IEP', 'el coordinador de educación especial de la escuela'],
      ],
    },
    ev_work_off: {
      ev: true,
      h: 'Pida la constancia de trabajo',
      p: 'Una carta, talones de pago, impuestos.',
      why: 'La historia laboral está en la lista de factores al decidir sobre la fianza.',
      how: [
        'Una carta con el puesto, la antigüedad y la nota de que el lugar se conserva',
        'Talones de pago de varios meses',
        'W-2 o 1099 de todos los años',
        'Reúna a medida que lleguen, no lo deje para después',
      ],
      src: [
        ['Talones de pago', 'recursos humanos o el sistema de nómina — ADP, Paychex'],
        ['Transcripciones de impuestos', 'irs.gov/individuals/get-transcript'],
      ],
    },
    ev_work_cash: {
      ev: true,
      h: 'Reúna la prueba de ingresos sin carta del empleador',
      p: 'El trabajo en efectivo también se puede documentar.',
      why: 'No tener empleador formal no significa no tener pruebas — se reúnen de otras fuentes.',
      how: [
        'Transferencias y depósitos en la cuenta',
        'Mensajes con los clientes',
        'Recibos, facturas, fotos de las obras',
        'Confirmación por escrito de los clientes',
      ],
      src: [
        ['El historial de envíos', 'la aplicación Remitly, Wise, Western Union'],
        ['Estados de cuenta por mes', 'la cuenta del banco'],
        ['Transcripciones de impuestos, si se presentaron', 'irs.gov/individuals/get-transcript'],
        ['La carta de asignación del ITIN — el número para pagar impuestos cuando no hay SSN', 'de su propio archivo de documentos'],
      ],
    },
    ev_work_own: {
      ev: true,
      h: 'Reúna los documentos de su negocio',
      p: 'Registro, facturas, contratos, impuestos.',
      why: 'El negocio propio prueba tanto la ocupación como el lazo con el lugar.',
      how: [
        'Documentos de registro',
        'Contratos con clientes y proveedores',
        'Declaraciones de impuestos',
        'La renta del local o del equipo',
      ],
    },
    ev_courts: {
      ev: true,
      h: 'Reúna las constancias de asistencia a la corte',
      p: 'Si hubo citas y usted fue a ellas — eso está a su favor.',
      why: 'La historia de asistencia a la corte está en la lista de factores. El juez mira si la persona fue cuando la citaron.',
      how: [
        'Las notificaciones de audiencias',
        'Las constancias de asistencia',
        'Cualquier correspondencia con la corte',
        'El expediente completo del caso anterior',
      ],
    },
    ev_crim: {
      ev: true,
      h: 'Pida constancias de la corte de todos los casos',
      p: 'Documentos oficiales, no recuerdos.',
      why: 'Los antecedentes están en la lista de factores, y el abogado necesita constancias oficiales de disposición para evaluar la situación. Un relato de memoria no sirve.',
      how: [
        'Pida el certificate of disposition en la corte donde fue el caso',
        'Hacen falta todos los casos, incluso viejos y cerrados',
        'Si hay varios casos — uno por cada uno',
        'Si después del caso hubo programas, cursos, voluntariado — reúna también esas constancias',
        'Esto toma tiempo, empiece ya',
      ],
      warn: 'No hable de los detalles por la línea telefónica grabada del centro. Ese es un tema para el abogado.',
    },
    lawyer_ready: {
      pages: ['attorney'],
      h: 'Decida con tiempo a qué abogado llamar',
      p: 'En el momento de la detención ya es tarde para buscar — el número ya debe existir.',
      why: 'El abogado de oficio no existe en el proceso de inmigración. Cuando el contacto está elegido de antemano, el primer día se va en el caso y no en la búsqueda — y la elección en pánico no lleva a un estafador. Según los datos de TRAC de 2026, la fianza se concede tres veces más a menudo con abogado: 42% de las audiencias frente a 14% sin representante.',
      how: [
        'Mire los dos caminos: organizaciones gratuitas y abogados de pago — las direcciones exactas están abajo',
        'Reúna 2–3 candidatos: la práctica es federal, se puede buscar por idioma y no por ciudad',
        'Verifique a cada uno en los tres registros — toma tres minutos',
        'Una consulta con tiempo es la forma de conocerse y entender la situación antes del problema',
        'El número del abogado elegido — a la tarjeta que se aprende de memoria y a la persona de confianza',
      ],
      src: [
        ['GRATIS · la lista pro bono de EOIR por estados', 'justice.gov/eoir/list-pro-bono-legal-service-providers'],
        ['GRATIS · el catálogo de ayuda gratuita y de bajo costo', 'immigrationlawhelp.org'],
        ['GRATIS · preguntar a un abogado en línea', 'americanbar.org/groups/legal_services/flh-home'],
        ['DE PAGO · búsqueda de AILA con filtro por idioma', 'ailalawyer.com'],
        ['VERIFICAR A CUALQUIERA · la lista disciplinaria de EOIR', 'justice.gov/eoir/list-of-currently-disciplined-practitioners'],
      ],
      info: 'En qué se diferencian. Gratis — organizaciones sin fines de lucro y representantes acreditados del Departamento de Justicia: es ayuda plenamente legítima, pero hay filas y no toman a todos. De pago — un abogado con contrato escrito, con tarifa o precio por fase, normalmente disponible más rápido. A unos y otros se les verifica en los mismos registros.',
    },
    community: {
      ev: true,
      h: 'Reúna las pruebas de participación en la comunidad',
      p: 'La parroquia, organizaciones, voluntariado, las actividades de los hijos.',
      why: 'Los lazos con la comunidad están en la lista de factores al decidir sobre la fianza. Este expediente crece con el tiempo: cuanto antes se empieza, más completo queda.',
      how: [
        'Una carta o constancia de participación de la parroquia',
        'Membresía en organizaciones, ligas, clubes',
        'Voluntariado — constancias de las organizaciones',
        'Las actividades y clubes de los hijos: recibos y constancias',
        'Fotos con fecha de eventos de la comunidad',
      ],
    },
    support_letters: {
      ev: true,
      h: 'Encuentre personas para cartas de apoyo',
      p: 'El empleador, los vecinos, la parroquia, las organizaciones.',
      why: 'Los abogados suelen incluir cartas de apoyo en el paquete para la audiencia: dan fe de los lazos y la reputación. Pedirlas a última hora es tarde — la gente necesita tiempo para escribir.',
      how: [
        'Haga una lista: el empleador, un vecino, el sacerdote, el entrenador de los hijos, un compañero de trabajo',
        'Pida el consentimiento con tiempo — una persona necesita varios días',
        'Una carta firmada con los contactos del autor — no una anónima',
        'La forma y el contenido los determina el abogado; su parte es encontrar a la gente y reunir los contactos',
      ],
      say: 'Buenos días. Nuestra familia va a necesitar cartas de apoyo para un caso. El abogado explicará la forma — de usted solo hace falta el consentimiento y un poco de tiempo. ¿Puedo pasar su contacto al abogado?',
      warn: 'No redactamos cartas para la corte. Qué debe ir exactamente en la carta lo determina el abogado según el caso concreto.',
    },
    bond_first: {
      pages: ['bondpay', 'sponsor'],
      h: 'Primero averigüe si habrá audiencia de fianza',
      p: 'El derecho a tenerla se está disputando en las cortes.',
      why: 'Desde julio de 2025 la posición del gobierno es que una persona que entró al país sin inspección está sujeta a detención obligatoria y no tiene fianza. Las cortes federales de apelación se dividieron: el Segundo, Tercer y Sexto Circuito no estuvieron de acuerdo; el Quinto y el Octavo apoyaron al gobierno (la decisión de un panel del Quinto Circuito a favor de las audiencias, del 2 de julio de 2026, fue anulada por el pleno; nueva revisión en septiembre). El Quinto Circuito es Texas, Luisiana y Misisipi — adonde más trasladan a la gente. La Corte Suprema tratará la cuestión en octubre de 2026. Conclusión: la respuesta depende de dónde está detenida la persona, y cambia con un traslado a otro estado.',
      how: [
        'Haga esta pregunta al abogado primero, antes que todo lo demás',
        'Averigüe en qué circuito está el centro',
        'Pregunte qué cambia si trasladan a la persona a otro estado',
        'Solo después decida si buscar a quien pague la fianza',
        'Prepare dos planes en paralelo: para la salida y para una detención que dure meses',
      ],
      info: 'La fianza no es el único mecanismo de salida. Existen también el parole (liberación discrecional por decisión de ICE), las mociones de revisión y la petición federal de habeas corpus — el camino que más crece en 2026: los abogados de AILA lo llaman, para muchos, el único que funciona en la práctica. Qué mecanismos aplican a un caso concreto lo determina solo el abogado.',
      src: [
        ['Si aún no hay abogado · ayuda gratuita por estados', 'justice.gov/eoir/list-pro-bono-legal-service-providers'],
        ['El catálogo de ayuda gratuita y de bajo costo', 'immigrationlawhelp.org'],
        ['Búsqueda de pago con filtro por idioma', 'ailalawyer.com'],
      ],
      warn: 'Solo un abogado puede determinar si esto aplica a una persona concreta. Aquí se describe el estado de la disputa a julio de 2026 — cambia rápido, mire la fecha.',
    },
    sponsor_ready: {
      pages: ['sponsor'],
      h: 'Prepare los documentos de quien pagará la fianza',
      p: 'Va a necesitar la prueba de su estatus.',
      why: 'La fianza la puede pagar un ciudadano de EE. UU. o titular de green card mayor de 18, y también bufetes y organizaciones sin fines de lucro.',
      how: [
        'Pasaporte de EE. UU., acta de nacimiento o green card',
        'La misma escritura de sus datos en el documento, la cuenta bancaria y el perfil',
        'Disposición a pagar por transferencia',
        'Avísele: el abogado puede pedirle también una carta de apoyo',
      ],
    },
    sponsor_talk: {
      pages: ['sponsor'],
      h: 'Hable con tiempo con quien podría pagar la fianza',
      p: 'Es una conversación dura; mejor no empezarla el día de la audiencia.',
      why: 'Personas con el estatus adecuado suele haber muy pocas, y la petición es seria — por eso se pospone hasta el final. La conversación es más fácil mostrando los dos caminos: la suma completa pagada por uno mismo — que se devuelve al final del caso, o a través de una compañía de fianzas — se paga solo un porcentaje, pero no se devuelve.',
      how: [
        'Explique que el dinero se devuelve al final del caso',
        'Diga con honestidad: puede tardar años',
        'Si la suma completa es demasiado, cuente el segundo camino: la compañía de fianzas la paga por un porcentaje que no se devuelve',
        'Avise que harán falta sus documentos',
        'Dele tiempo para pensar',
      ],
      say: 'Necesito pedirte algo serio. Para que suelten a una persona, la fianza la debe pagar un ciudadano o alguien con green card — yo no puedo hacerlo. El dinero se devuelve cuando termina el caso, pero puede tardar mucho. Si la suma completa es demasiado, hay un camino con una compañía de fianzas: se paga solo un porcentaje, pero no se devuelve. Entenderé cualquier respuesta. ¿Puedo explicarte cómo funciona?',
      warn: 'No prometa plazos de devolución — no dependen ni de usted ni de él.',
    },
    bondfund: {
      pages: ['sponsor'],
      h: 'Mire los fondos de fianza y las compañías de fianzas',
      p: 'La fianza la puede pagar una organización, no solo alguien cercano.',
      why: 'Si no hay personas adecuadas, quedan dos caminos sin ellas: un fondo de fianza sin fines de lucro — o una compañía comercial, que paga la fianza por un porcentaje que no se devuelve. Para muchos son las únicas opciones.',
      how: [
        'Busque fondos que trabajen en este estado',
        'Confirme si toman este centro',
        'Pregunte por la fila de espera y las condiciones',
        'La compañía de fianzas es el segundo camino: se paga un porcentaje y no se devuelve; cada empresa tiene sus requisitos — compare condiciones por escrito',
        'Verifique la organización en los mismos registros que a un abogado',
      ],
      warn: 'Los fondos cambian, algunos cierran. Asegúrese de que la organización funciona ahora.',
    },
    school_add: {
      h: 'Agregue a una segunda persona en la escuela',
      p: 'Ahora mismo solo un adulto puede recoger al niño.',
      why: 'La escuela entrega al niño solo a quienes están en su tarjeta. Se arregla con un formulario en la oficina y no requiere corte.',
      how: [
        'Vaya a la oficina de la escuela en persona',
        'Pida el formulario de authorized pickup o emergency contact',
        'Lleve un documento con foto',
        'Pida una copia del formulario lleno para usted',
        'Indique aparte a quién no se le puede entregar',
      ],
      say: 'Buenos días. Quiero agregar a una persona a la lista de quienes pueden recoger al niño y actualizar los contactos de emergencia. ¿Me dice qué formulario lleno?',
    },
    caregiver: {
      h: 'Arregle el documento del cuidado de los niños',
      p: 'Un familiar recibe la posibilidad de llevarlos a la escuela y al médico sin corte.',
      why: 'En California, el Caregiver’s Authorization Affidavit permite a un familiar inscribir al niño en la escuela y dar consentimiento médico. No hace falta la tutela por corte.',
      form: 'Es un formulario establecido por ley. No lo redactamos — use el formato oficial. No quita los derechos de los padres.',
      warn: 'Fuera de California el procedimiento es distinto. Revise las reglas del estado.',
    },
    caregiver_risk: {
      h: 'Encuentre para los niños a un adulto con estatus',
      p: 'El cuidador no debe estar él mismo en riesgo de detención.',
      why: 'Si la persona asignada a cuidar a los niños no tiene estatus, el plan puede caerse el mismo día. Las organizaciones aconsejan elegir a un ciudadano o titular de green card.',
      how: [
        'Haga una lista de adultos adecuados',
        'Hable con tiempo, no lo ponga ante el hecho',
        'Asegúrese de que sabe dónde están los documentos',
        'Que se aprenda los teléfonos necesarios',
      ],
    },
    dep_plan: {
      h: 'Piense quién cuidará a los dependientes',
      p: 'Los mayores y los enfermos quedan sin cuidado el mismo día.',
      why: 'Los planes de preparación suelen armarse alrededor de los niños, y los adultos a cargo quedan fuera. El cuidado se corta de inmediato.',
      how: [
        'Quién viene y con qué frecuencia',
        'Dónde están los medicamentos y las recetas',
        'Quién puede hablar con los médicos',
        'Quién paga y con qué',
      ],
    },
    meds_list: {
      h: 'Haga la lista de medicamentos',
      p: 'Nombres y dosis, no «pastillas para la presión».',
      why: 'En el centro hay que nombrar los medicamentos con exactitud. Una pausa en la toma es un riesgo real para la salud.',
      how: [
        'Nombres completos y dosis',
        'Contactos de los médicos tratantes',
        'Diagnósticos, si hay documentos',
        'Pida al médico copias de los registros médicos — también sirven para el caso',
        'Lleve una copia consigo y deje otra a una persona de confianza',
      ],
    },
    hipaa: {
      h: 'Arregle el acceso a la información médica',
      p: 'Sin él, un familiar no podrá hablar con los médicos.',
      why: 'El formulario HIPAA es un papel con el que la persona permite a los médicos hablar de su salud con quien está nombrado ahí. Con la forma firmada, la persona de confianza puede recibir los registros médicos y hablar con los médicos. Hace falta para la salud y como prueba para el caso.',
      form: 'El formato lo da el centro médico; el formulario es estándar. No lo redactamos. El formulario para el hospital y el consentimiento para que la agencia comparta información son papeles distintos.',
    },
    poa: {
      h: 'Resuelva el poder notarial',
      p: 'Un documento cubre el carro, la cuenta y los contratos.',
      why: 'Los bienes a nombre de una sola persona quedan inaccesibles para los demás. El carro no se puede vender, la cuenta no se puede manejar, el contrato no se puede pasar.',
      form: 'El poder es un documento legal. No lo redactamos y no damos modelos. El orden habitual: se toma el formulario oficial del estado o el formulario del propio banco, se llena, y la firma se certifica — en California ante un notary public o con dos testigos. Ojo: en EE. UU. el notary public solo certifica firmas — no es abogado y no redacta documentos. Si la persona ya está detenida — el procedimiento de firma es otro; esa es una pregunta para el abogado.',
      how: [
        'Defina qué es exactamente lo que hay que cubrir',
        'Confirme si el banco o la agencia exige su propio formulario',
        'Haga copias y diga dónde está el original',
      ],
    },
    payments: {
      h: 'Haga la lista de pagos obligatorios',
      p: 'Con fechas y montos. Alguien tiene que cubrirlos.',
      why: 'Las moras empiezan en silencio: la renta, el préstamo del carro, el seguro. En unas semanas se llevan el carro y se pierde la vivienda.',
      how: [
        'Anote todos los pagos regulares con fechas',
        'Marque de dónde se cobran',
        'Marque quién tiene acceso a ese dinero',
        'Empiece por el de fecha más cercana',
      ],
    },
    phones: {
      pages: ['firstcall'],
      h: 'Apréndase de memoria dos números de teléfono',
      p: 'El teléfono es lo primero que quitan.',
      why: 'Las organizaciones de ayuda lo ponen entre los primeros pasos: sin un número aprendido, la persona en el centro no puede llamar a nadie, aun teniendo la posibilidad de llamar.',
      how: [
        'Un número de una persona cercana',
        'El segundo — de un abogado o una organización',
        'Verifique que los recuerda sin ayuda',
        'Anótelos también en papel y guárdelo aparte del teléfono',
      ],
    },
    docs_gather: {
      h: 'Reúna los documentos en una carpeta',
      p: 'Y haga copias.',
      why: 'Los originales se pierden: quedan en el carro, en la vivienda, se van con la persona.',
      how: [
        'Pasaportes, actas de nacimiento y de matrimonio',
        'Todos los documentos y cartas de inmigración',
        'Registros médicos y escolares',
        'Fotografíe todo, incluidos los reversos',
      ],
    },
    copies_trusted: {
      h: 'Entregue copias a una persona de confianza',
      p: 'Guarde los originales aparte.',
      why: 'Las organizaciones aconsejan guardar copias donde una persona confiable pueda alcanzarlas si usted no está.',
      how: [
        'Elija a una persona que no esté ella misma en riesgo',
        'Entregue las copias y diga dónde están los originales',
        'Duplique en la nube',
      ],
      warn: 'El plan y los documentos no se llevan encima. Guárdelos en un lugar seguro, y dónde — solo lo saben personas de confianza.',
    },
    trusted_setup: {
      h: 'Póngase de acuerdo con su persona de confianza',
      p: 'No «a quién llamar», sino quién va a actuar.',
      why: 'Los papeles reunidos no valen nada si nadie sabe que existen y dónde están. La detención llega de golpe, y después actúa no quien se llevaron, sino quien quedó.',
      how: [
        'Elija a una persona que no esté ella misma en riesgo de detención',
        'Muéstrele dónde están los documentos y las copias',
        'Que se aprenda su número A',
        'Acuerden a quién llama primero',
        'Diga quién recoge a los niños y quién sabe de los medicamentos',
      ],
      say: 'Quiero pedirte algo, por si acaso. Si algo me pasa y dejo de estar en contacto — aquí están mis documentos, a estas personas hay que llamar. Espero que no haga falta. ¿Te lo puedo mostrar?',
      warn: 'No lleve el plan y los documentos encima. Guárdelos en un lugar confiable, y dónde exactamente — solo lo saben personas de confianza.',
    },
    trusted_find: {
      h: 'Encuentre a la persona que va a actuar',
      p: 'Mientras no exista, toda la preparación descansa solo en usted.',
      why: 'Si nadie sabe de su situación, en el primer día después de la detención no pasará nada: nadie lo buscará, nadie sacará los documentos, nadie recogerá a los niños.',
      how: [
        'Sirven un compañero de trabajo, un vecino, alguien de la comunidad o la parroquia',
        'No tiene que ser familiar ni amigo cercano',
        'Lo importante es que acepte y no esté él mismo en riesgo',
        'Con una persona basta, pero dos es mejor',
      ],
    },
    court_dates: {
      pages: ['deadlines'],
      h: 'Tenga las fechas de audiencia bajo control',
      p: 'Faltar a una audiencia es la pérdida irreversible más común.',
      why: 'Si la persona no llega a una audiencia programada, el caso puede decidirse sin ella y en ausencia. La mayoría de las veces no es por fuga sino por un cambio de dirección: la notificación llega a la vieja.',
      how: [
        'Revise la fecha de su audiencia en el sistema oficial',
        'Ponga recordatorios 14, 3 y 1 día antes',
        'Al mudarse, presente el cambio de dirección a la corte con el formulario aparte EOIR-33',
        'Guarde la constancia de la presentación',
      ],
      src: [
        ['Revisar la fecha de la audiencia', 'acis.eoir.justice.gov'],
        ['El formulario de cambio de dirección', 'justice.gov/eoir/form-eoir-33'],
      ],
    },
    prior_case: {
      h: 'Consiga los documentos del caso anterior',
      p: 'Lo que pasó antes determina muchísimo.',
      why: 'Una detención pasada o un caso cerrado deja huella en el sistema, y el abogado necesita documentos, no recuerdos. Es lo primero que va a preguntar.',
      how: [
        'Todas las notificaciones y decisiones del caso anterior',
        'El número del caso anterior, si se conserva',
        'Si no hay papeles — un pedido a la corte o a través del abogado',
        'Fotografíe todo lo que encuentre',
      ],
      warn: 'No hable de casos anteriores por la línea telefónica grabada del centro. Ese es un tema para el abogado.',
    },
    connect: {
      pages: ['connect'],
      h: 'Arregle el contacto y el dinero para llamadas',
      p: 'Dos formas de pagar, y la diferencia de costo es considerable.',
      why: 'No se puede llamar hacia adentro — solo él llama. Mientras no haya dinero en la cuenta, no hay contacto. El contacto cálido y regular es lo que más protege a una persona adentro.',
      how: [
        'Averigüe qué operador de teléfono tiene ese centro',
        'Opción 1: recargar el saldo personal del detenido — él llama a quien quiera',
        'Opción 2: vincular una cuenta a su número — llamadas solo a usted, normalmente cuesta menos',
        'Ponga el número A en todo lo que envíe',
      ],
      src: [
        ['Las aplicaciones de los operadores', 'GettingOut · Securus · ConnectNetwork'],
        ['Cartas y postales a los centros', 'pigeon.ly'],
      ],
      form: 'Importante sobre la recarga: en la aplicación GettingOut no se puede poner dinero — la aplicación muestra el saldo y los mensajes, pero el pago no funciona en ella. Hay que recargar por el sitio web del operador en el navegador, desde una computadora o el teléfono. Con otros operadores pasa igual — si la aplicación no tiene botón de pago, busque el sitio, no reinstale la aplicación.',
      warn: 'Libros — solo nuevos y directamente de una tienda o editorial, no de un particular. La pasta blanda pasa más rápido: la dura tarda más en revisarse y muchas veces no entra. Cada centro tiene sus reglas — confirme por teléfono antes de enviar.',
    },
    money: {
      pages: ['state-ca'],
      h: 'Mire dónde consiguen el dinero las familias',
      p: 'La fianza, el abogado, la renta — los gastos llegan juntos. Los mecanismos existen.',
      why: 'Las colectas por GoFundMe y las redes de apoyo mutuo son un mecanismo reconocido: las familias reúnen decenas de miles de dólares para la fianza y el abogado. Pedir ayuda públicamente aquí es normal — lo hacen cientos de familias.',
      how: [
        'Una colecta (GoFundMe y similares): describa la situación con honestidad, con la meta y el monto — fianza, abogado, renta',
        'Pida a la parroquia, a una organización, a los compañeros que la compartan — la colecta funciona por confianza, no con desconocidos',
        'Redes de apoyo mutuo en comunidades e iglesias — pregunte en la suya',
        'Fondos de fianza — en la página del estado',
        'Anote lo reunido y lo gastado: la confianza de los donantes es el recurso principal de la colecta',
      ],
      warn: 'No damos consejos financieros y no recolectamos dinero. Verifique a quién le envía: la colecta debe llevarla una persona que usted conoce en persona.',
    },
    support: {
      h: 'Reparta la carga y manténgase cerca de la gente',
      p: 'El miedo y el insomnio aquí son una reacción normal.',
      why: 'Los casos duran meses. Quien carga con todo solo se quema antes de que termine el proceso. La aplicación es una herramienta, no un reemplazo del apoyo humano.',
      how: [
        'Reparta las tareas entre los familiares, no lo tome todo usted',
        'Mantenga sus rutinas: sueño, comida, trabajo',
        'Apóyese en la gente viva de al lado',
      ],
      src: [
        ['La línea de crisis, las 24 horas y gratis', '988 — llamada o mensaje'],
        ['Crisis Text Line', 'envíe HOME al 741741'],
        ['Ante un peligro inmediato', '911'],
      ],
      warn: 'Esto es información general de referencia, no ayuda médica ni psicológica.',
    },
    nosign: {
      pages: ['documents'],
      h: 'No firmar nada sin abogado',
      p: 'Algunos documentos significan renunciar a la corte.',
      why: 'La salida voluntaria y la orden estipulada significan aceptar irse y renunciar a la audiencia. Después de firmar, el caso no llega al juez.',
      how: [
        'Transmita esto en la primera conversación',
        'La fórmula es simple: no firmo nada sin abogado',
        'Pregunte si ya firmó algo, y qué exactamente',
      ],
      warn: 'ACLU, FIRRP e ILRC publican la recomendación de no firmar documentos antes de hablar con un abogado y dar solo el nombre propio.',
    },
    verify: {
      pages: ['verify'],
      h: 'Verifique a quién le paga, antes de pagar',
      p: 'Tres registros oficiales, tres minutos.',
      why: 'En EE. UU. el notario no es abogado y no puede representar en la corte de inmigración. En América Latina el notario público sí es abogado. Sobre esa diferencia está construido el fraude más común.',
      how: [
        'El colegio de abogados del estado — licencia vigente',
        'El registro de representantes acreditados del Departamento de Justicia',
        'La lista disciplinaria de EOIR',
      ],
      src: [
        ['La lista disciplinaria de EOIR', 'justice.gov/eoir/list-of-currently-disciplined-practitioners'],
        ['Búsqueda de abogado con filtro por idioma', 'ailalawyer.com'],
      ],
      warn: 'Señales de alarma: promesa de salida en una fecha concreta, garantía del resultado, pago adelantado en efectivo sin contrato, negarse a dar el número de licencia.',
    },
    freehelp: {
      pages: ['attorney'],
      h: 'Busque una consulta legal gratuita',
      p: 'Las organizaciones sin fines de lucro hacen evaluaciones gratuitas.',
      why: 'Las organizaciones mantienen catálogos nacionales de ayuda migratoria gratuita y de bajo costo. La evaluación ayuda a entender qué opciones existen en general.',
      how: [
        'Llame a varias a la vez — en todas hay filas',
        'Pregunte si toman casos de detenidos',
        'Confirme si trabajan con ese centro',
      ],
      src: [
        ['La lista pro bono de EOIR por estados', 'justice.gov/eoir/list-pro-bono-legal-service-providers'],
        ['El catálogo de ayuda gratuita y de bajo costo', 'immigrationlawhelp.org'],
        ['Respuestas gratuitas de abogados', 'americanbar.org/groups/legal_services/flh-home'],
      ],
      warn: 'El abogado de oficio no existe en el proceso de inmigración. La ayuda gratuita existe, pero con filas.',
    },
  },

  reasons: {
    anum_have: 'el número se conoce',
    anum_find_docs: 'hay documentos en casa',
    anum_none: 'no hay número',
    idb: 'faltan datos para la búsqueda',
    urgent: 'la persona ya está detenida',
    money: 'los gastos llegan juntos — fianza, abogado, renta',
    freehelp: 'hace falta una evaluación legal',
    support: 'el caso va para largo',
    trusted_yes: 'hay una persona de confianza',
    trusted_maybe: 'no hay acuerdo',
    trusted_no: 'no hay quien actúe por usted',
    case_open: 'el caso en la corte sigue',
    prior: 'lo detuvieron antes',
    home_has: 'hay contrato de vivienda',
    home_none: 'no hay contrato — hacen falta otras pruebas de dirección',
    years: 'tiempo de residencia',
    family: 'hay familiares con estatus',
    community: 'los lazos con la comunidad son parte del expediente',
    support_letters: 'las cartas suelen pedirse para la audiencia',
    work_off: 'trabajo formal',
    work_cash: 'trabajo en efectivo',
    work_own: 'negocio propio',
    courts: 'hubo citas en la corte',
    crim: 'hubo arrestos',
    bond_first: 'el derecho a la fianza está en disputa',
    lawyer_ready: 'el abogado se busca antes de la detención, no después',
    sponsor_yes: 'hay quien pague la fianza',
    sponsor_maybe: 'quién paga la fianza — todavía en duda',
    sponsor_no: 'no hay personas adecuadas',
    school_only: 'en la escuela figura un solo adulto',
    guard_status: 'hay un adulto con estatus',
    guard_risk: 'el cuidador está en riesgo o no existe',
    dep: 'hay dependientes además de los niños',
    meds: 'toma medicamentos',
    hipaa: 'el acceso a los médicos no está arreglado',
    sole: 'los bienes están a nombre de una sola persona',
    pay: 'hay pagos regulares',
    phones: 'los teléfonos no están aprendidos',
    docs_has: 'los documentos existen',
    docs_none: 'los documentos no aparecen',
    copies: 'la persona de confianza no tiene copias',
  },
}

export default c
