#!/usr/bin/env node
// CN-RESEARCH (§23, D-071): aggregator for the "Verified audit market" report.
//
// The report analyses the ONE original, verified dataset AccessAtlas actually
// has — its own 245-agency catalog (data/a11y/agencies.json) — NOT a benchmark
// of external websites: the sandbox browser cannot reach external HTTPS (D-010)
// and no mass scan exists, so any "accessibility index of the top-100 sites"
// would require invented numbers, which D-045/D-047 forbid.
//
// Every number rendered on /reports/verified-audit-market comes from computeStats
// below — computed from agencies.json at build time, never typed by hand (the
// same discipline as scripts/en301549-coverage.mjs). The committed snapshot
// data/a11y/reports.json is regenerated by running this file; scripts/
// reports-data.test.mjs recomputes from agencies.json and fails if the snapshot
// drifts or was hand-edited, so a stale or fabricated figure cannot ship.
//
// Run: node scripts/reports-data.mjs   (writes data/a11y/reports.json)

import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')

// Every declarant / cert kind / price band that the schema allows, so a class
// that happens to be empty is reported as an explicit 0, not silently omitted.
const DECLARANTS = ['public-body', 'private', 'unknown']
const CERT_KINDS = [
  'statement-named-auditor',
  'bitv-pruefstelle',
  'iaap-org-member',
  'dhs-trusted-tester',
  'iaap-certified-staff',
]
const PRICE_BANDS = ['budget', 'mid', 'premium', 'enterprise']

const bump = (obj, key) => {
  obj[key] = (obj[key] ?? 0) + 1
}

const median = (nums) => {
  if (!nums.length) return null
  const s = [...nums].sort((a, b) => a - b)
  const mid = Math.floor(s.length / 2)
  return s.length % 2 ? s[mid] : Math.round((s[mid - 1] + s[mid]) / 2)
}

/**
 * Pure aggregator: agencies + taxonomies → deterministic stats. No I/O, no
 * clock — same input always yields byte-identical output, which is what lets
 * the test assert the committed snapshot against a fresh recompute.
 */
export function computeStats(agencies, taxonomies) {
  const countryName = (code) => taxonomies?.countries?.[code]?.name?.en ?? code
  const standardLabel = (slug) => taxonomies?.standards?.[slug]?.label?.en ?? slug

  // Where the listed agencies are headquartered ("who's listed").
  const hqCounts = {}
  for (const a of agencies) bump(hqCounts, a.hq?.countryCode ?? 'unknown')
  const hqDistribution = Object.entries(hqCounts)
    .map(([code, count]) => ({ code, name: countryName(code), count }))
    .sort((x, y) => y.count - x.count || x.code.localeCompare(y.code))

  // Distinct countries the catalog covers by service area (HQ ∪ countriesServed).
  const served = new Set()
  for (const a of agencies) {
    if (a.hq?.countryCode) served.add(a.hq.countryCode)
    for (const c of a.countriesServed ?? []) if (!c.startsWith('remote-')) served.add(c)
  }

  // Standards each agency declares it works to.
  const stdCounts = {}
  for (const a of agencies) for (const s of a.standards ?? []) bump(stdCounts, s)
  const standards = Object.entries(stdCounts)
    .map(([slug, count]) => ({ slug, label: standardLabel(slug), count }))
    .sort((x, y) => y.count - x.count || x.slug.localeCompare(y.slug))

  // Price band: we publish a band only where it is verifiable; the honest
  // majority is "no published band", never a guessed number (D-045).
  const bandDist = Object.fromEntries(PRICE_BANDS.map((b) => [b, 0]))
  let withBand = 0
  for (const a of agencies) {
    if (a.priceBand && PRICE_BANDS.includes(a.priceBand)) {
      bump(bandDist, a.priceBand)
      withBand++
    }
  }

  // Evidence: which records carry a verifiable credential, and — for the
  // strongest class, being named as the auditor in a published accessibility
  // statement — who published that statement (D-042).
  const certKinds = Object.fromEntries(CERT_KINDS.map((k) => [k, 0]))
  const namedAuditorByDeclarant = Object.fromEntries(DECLARANTS.map((d) => [d, 0]))
  let recordsWithAnyCert = 0
  let recordsWithNamedAuditorStatement = 0
  for (const a of agencies) {
    const certs = a.certs ?? []
    if (certs.length) recordsWithAnyCert++
    let named = false
    for (const c of certs) {
      if (c.kind in certKinds) bump(certKinds, c.kind)
      if (c.kind === 'statement-named-auditor') {
        named = true
        const d = DECLARANTS.includes(c.declarant) ? c.declarant : 'unknown'
        bump(namedAuditorByDeclarant, d)
      }
    }
    if (named) recordsWithNamedAuditorStatement++
  }

  // Founded year: reported only where verified (D-051..D-053), never inferred.
  const years = agencies.map((a) => a.founded).filter((y) => typeof y === 'number')

  // Sources: every record must carry ≥1 source ref (schema invariant); we also
  // report how many stand on more than one.
  const refCounts = agencies.map((a) => (a.sourceRefs ?? []).length)
  const totalRefs = refCounts.reduce((s, n) => s + n, 0)

  return {
    source: 'data/a11y/agencies.json',
    total: agencies.length,
    hqCountries: { count: hqDistribution.length, distribution: hqDistribution },
    countriesCovered: served.size,
    standards,
    priceBands: { withBand, withoutBand: agencies.length - withBand, distribution: bandDist },
    evidence: {
      recordsWithAnyCert,
      recordsWithNamedAuditorStatement,
      namedAuditorByDeclarant,
      certKinds,
    },
    founded: {
      withYear: years.length,
      withoutYear: agencies.length - years.length,
      oldest: years.length ? Math.min(...years) : null,
      newest: years.length ? Math.max(...years) : null,
      median: median(years),
    },
    sources: {
      totalRefs,
      recordsWithMultiple: refCounts.filter((n) => n >= 2).length,
      minPerRecord: refCounts.length ? Math.min(...refCounts) : 0,
      everyRecordHasAtLeastOne: refCounts.every((n) => n >= 1),
    },
  }
}

export function loadInputs() {
  const agencies = JSON.parse(readFileSync(join(ROOT, 'data/a11y/agencies.json'), 'utf8'))
  const taxonomies = JSON.parse(readFileSync(join(ROOT, 'data/a11y/taxonomies.json'), 'utf8'))
  return { agencies, taxonomies }
}

// Stable 2-space JSON with a trailing newline, so regeneration produces a
// minimal, reviewable diff.
export const serialize = (stats) => JSON.stringify(stats, null, 2) + '\n'

const isMain = process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]
if (isMain) {
  const { agencies, taxonomies } = loadInputs()
  const stats = computeStats(agencies, taxonomies)
  const out = join(ROOT, 'data/a11y/reports.json')
  writeFileSync(out, serialize(stats))
  console.log(
    `✓ reports-data: ${stats.total} agencies · ${stats.hqCountries.count} HQ countries · ` +
      `${stats.evidence.recordsWithNamedAuditorStatement} named-auditor statements · → data/a11y/reports.json`,
  )
}
