import type { UIStrings } from '@/lib/types'

const ui: UIStrings = {
  back: '← Back',
  listen: 'Listen to this page',
  stop: 'Stop',
  noSpeech: 'This browser cannot read aloud',
  allPages: 'All pages',
  disclaimer:
    'We are not attorneys and we do not give legal advice. This page has facts and links to official sources only.',
  updated: 'Information updated July 28, 2026. Rules change — check the date.',
  nav: {
    where: 'How to find him',
    anum: 'Where to find the A-Number',
    documents: 'What these papers mean',
    firstcall: 'The first call',
    verify: 'Check the attorney',
    connect: 'Calls, money, letters',
    journey: 'The road',
    attorney: 'Attorney',
    habeas: 'Habeas corpus',
    docpack: 'Package for the attorney',
    deadlines: 'Do not miss a hearing',
    intake: 'Your task list',
    'facility-adelanto': 'Adelanto',
    'state-ca': 'California',
    'state-tx': 'Texas',
    'state-la': 'Louisiana',
    orgs: 'For organizations',
    about: 'About',
    data: 'Your data',
    disclaimer: 'We are not lawyers',
  },
  navGroups: [
    { label: 'The first night', keys: ['intake', 'where', 'anum', 'documents', 'firstcall', 'verify'] },
    { label: 'The road', keys: ['journey', 'connect', 'attorney', 'habeas', 'docpack', 'deadlines'] },
    { label: 'Directory', keys: ['state-ca', 'state-tx', 'state-la', 'facility-adelanto'] },
    { label: 'About', keys: ['orgs', 'about', 'data', 'disclaimer'] },
  ],
  iceGate: {
    title: 'You are about to open the ICE website',
    body: [
      'According to its own privacy notice, it records the IP address and domain of every visitor.',
      'We do not send it any data about you.',
    ],
    open: 'Open',
    ask: 'Ask another person to do this',
    askHint: 'Forward this address to someone who can run the search for you:',
  },
  nameVariants: {
    label: 'Spelling variants of the name — everything stays in this browser',
    placeholder: 'First and last name as you know them',
    hint: 'The name must match letter for letter. Use the checkboxes to mark variants you have tried.',
    // min-ok: подпись инструмента, данные не покидают браузер
  },
  aNumber: {
    label: 'Check the A-Number format',
    placeholder: 'Digits only, 8 or 9',
    copy: 'Copy',
    copied: 'Copied',
    hint: 'Eight digits is fine too: a zero is added at the front. The number is printed on the wristband — you can ask for it to be read aloud.',
  },
  printPage: 'Print this page',
  dirEmpty: 'No data yet. We do not publish phone numbers or addresses we have not verified.',
  docPack: {
    // min-ok: подписи разделов инструмента, файлы не покидают браузер
    sections: {
      home: 'Address and housing',
      years: 'Years of residence',
      family: 'Family',
      work: 'Work',
      courts: 'Court appearances',
      court: 'Papers from the court and the agency',
      med: 'Medical',
      other: 'Other',
    },
    addPhoto: '+ Photo',
    processing: 'Processing…',
    labelPlaceholder: 'What it is and which year',
    remove: 'Remove',
    pages: ['page', 'pages', 'pages'],
    anumLabel: 'A-Number, if known — for the file name, without the person’s name',
    anumHint: 'Digits only, can be left empty',
    makePdf: 'Assemble the PDF package',
    making: 'Assembling…',
    empty: 'empty so far',
    share: 'Share',
    download: 'Download',
    print: 'Open to print',
    shareUnavailable: 'This device has no system "Share" — download the file and attach it yourself.',
    deleteAll: 'Delete all photos from the browser',
    deleteAllConfirm: 'Delete for sure? Tap again',
    storageNote: 'The photos are stored only in this browser. We do not see them and do not receive them. After sending the package you can delete them with one button.',
    readyTitle: 'The package is ready',
    readyHint: '"Share" opens your phone’s own menu: email, WhatsApp — whatever you use. Our server is not involved.',
    partLabel: 'Part',
    cover: {
      title: 'Document package for the attorney',
      date: 'Date',
      packet: 'Package no.',
      supplements: 'Supplements package no. {n} of {date}',
      noAnum: 'A-Number not provided',
      toc: 'What is inside',
      missing: 'What is still missing',
      missingNote: 'The list of gaps is more honest than the list of achievements: it saves the attorney the first conversation.',
      pagesWord: 'p.',
      part: 'Part {i} of {n}',
      footer: 'Assembled by the family in the browser via detnav.com. The files never passed through any server. We are not lawyers; what the package should contain is determined by the attorney.',
    },
  },
}

export default ui
